{} and “” around variables
Changes made for consistency. Curly brackets and quotes do not always make a difference in how the variables are evaluated, but making all variables the same allows for predictable execution. (I left in-script comments alone.)

diff --git a/_test4 b/_test4
--- a/_test4
+++ b/_test4
@@ -2,7 +2,7 @@
 
 
 while getopts ":o:b" OPT ; do
-    case $OPT in
+    case "${OPT}" in
         o)
             echo "-o was triggered"
             ;;
@@ -10,11 +10,11 @@ while getopts ":o:b" OPT ; do
             echo "fuck me! -b was triggered"
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            echo "Invalid option: -${OPTARG}" >&2
             exit 1
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            echo "Option -${OPTARG} requires an argument." >&2
             exit 1
             ;;
     esac
diff --git a/makeH264 b/makeH264
--- a/makeH264
+++ b/makeH264
@@ -10,16 +10,16 @@ bired=$(tput bold)$(tput setaf 1)
 color_off=$(tput sgr0)
 script_path=${0%/*}
 # script_path will be the directory path of {0} which is the script being called
-. "$script_path/nmaahcmmfunctions"
+. "${script_path}/nmaahcmmfunctions"
 # You can't directly call a function in another shell script.
 # You can move your function definitions into a separate file and then load them into your script using the . command, like this:
 # . /path/to/functions.sh
 # This will interpret functions.sh as if it's content were actually present in your file at this point.
 # This is a common mechanism for implementing shared libraries of shell functions.
-[[ -f "$script_path/nmaahcmmfunctions" ]] || { echo "Missing '$script_path/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 # will check to see that that nmaahcmmfunctions exists and if it doesn't (left side of || exits non-zero) then it will execute the right side of ||
 dependencies=(ffmpeg ffprobe)
-echo script path is $script_path
+echo "script path is ${script_path}"
 _initialize_make
 relativepath="derivative"
 suffix="" #suffix is blank here but can be filled in with desired characters for inlcusion in filename
@@ -75,22 +75,22 @@ makeh264 ()
 	#shift $(( ${OPTIND} - 1 ))
 	shift "$((OPTIND-1))"
 
-	input="$1" #set $input as the first arugment sent to script
-	if [[ -f "$input" ]] ; then #if input is a file, set output_dir to input name with extension stripped plus relativepath
+	input="${1}" #set $input as the first arugment sent to script
+	if [[ -f "${input}" ]] ; then #if input is a file, set output_dir to input name with extension stripped plus relativepath
 		output_dir="${input%.*}/$relativepath"
-  elif [[ -d "$input" ]]; then #if input is a directory, set output_dir to input name plus relativepath
-		output_dir="$input/$relativepath"
+  elif [[ -d "${input}" ]]; then #if input is a directory, set output_dir to input name plus relativepath
+		output_dir="${input}/$relativepath"
   fi
   mediaid="${input##*/}" #set $mediaid to basename of $input
 	mediaid="${mediaid%.*}" #set $mediaid to $mediaid with extension stripped
- 	output="$output_dir/${mediaid%.*}$suffix.$extension" #set $output
-	if [ -s "$output" ] ; then #check to see if $output exists
-		printf "%sWARNING $output already exists, skipping transcode of %s.%s%s\n" "$bired" "$input" "$color_off" "$biwhite"
+ 	output="${output_dir}/${mediaid%.*}$suffix.$extension" #set $output
+	if [ -s "${output}" ] ; then #check to see if $output exists
+		printf "%sWARNING ${output} already exists, skipping transcode of %s.%s%s\n" "${bired}" "${input}" "${color_off}" "${biwhite}"
 		shift
 	fi
-		printf "%smediaid is: %s%s\n" "$color_off" "$biwhite" "$mediaid"
-		printf "%sThe output directory is: %s%s\n" "$color_off" "$biwhite" "$output_dir"
-		printf "%soutput is: %s%s\n" "$color_off" "$biwhite" "${output_dir/$mediaid%.*$suffix.$extension}"
+		printf "%smediaid is: %s%s\n" "${color_off}" "${biwhite}" "${mediaid}"
+		printf "%sThe output directory is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir}"
+		printf "%soutput is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir/$mediaid%.*$suffix.$extension}"
 
 	echo
 cat <<-EOF
@@ -104,7 +104,7 @@ cat <<-EOF
 	If the output looks good, then try a higher value and if it looks bad then choose a lower value.
 EOF
 	echo
-	printf "%sPlease enter a CRF value:%s\n" "$color_off" "$biwhite"
+	printf "%sPlease enter a CRF value:%s\n" "${color_off}" "${biwhite}"
 	read -r crfvalue
 	echo
 cat <<-EOF
@@ -117,10 +117,10 @@ cat <<-EOF
 	The general guideline is to use the slowest preset that you have patience for.
 	Current presets in descending order of speed are:
 EOF
-	printf "%sultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow\n" "$bired"
-	#printf "%s" "$biwhite"
+	printf "%sultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow\n" "${bired}"
+	#printf "%s" "${biwhite}"
 	echo
-	printf "%sPlease enter a preset speed:%s\n" "$color_off" "$biwhite"
+	printf "%sPlease enter a preset speed:%s\n" "${color_off}" "${biwhite}"
 	read -r presetspeed
 	echo
 cat <<-EOF
@@ -128,19 +128,19 @@ cat <<-EOF
 	A good maxrate for Youtube type delivery is 8000.
 EOF
 	echo
-	printf "%sPlease enter a maxrate speed:%s\n" "$color_off" "$biwhite"
+	printf "%sPlease enter a maxrate speed:%s\n" "${color_off}" "${biwhite}"
 	read -r maxrate
-	printf "\n%smaking .mp4 derivative of %s%s%s\n" "$color_off" "$biwhite" "$mediaid" "$color_off" #have script say what is about to do
-	mkdir -p "$output_dir"
+	printf "\n%smaking .mp4 derivative of %s%s%s\n" "${color_off}" "${biwhite}" "${mediaid}" "${color_off}" #have script say what is about to do
+	mkdir -p "${output_dir}"
 
 	for file in $@ ; do
-		if [[ -f "$file" ]]; then #run ffmpeg command on $input and set output to $output
+		if [[ -f "${file}" ]]; then #run ffmpeg command on $input and set output to $output
 			# -vf scale=-2:1484
-			ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "$file" -movflags faststart -c:v libx264 -vf "yadif,format=yuv420p" -crf "$crfvalue" -preset "$presetspeed" -maxrate "$maxrate"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "$output"
-		elif [[ -d "$file" ]]; then
-			ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "$file"/*.mov -movflags faststart -pix_fmt yuv420p -c:v libx264 -crf "$crfvalue" -preset "$presetspeed" -maxrate "$maxrate"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "$output"
+			ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${file}" -movflags faststart -c:v libx264 -vf "yadif,format=yuv420p" -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
+		elif [[ -d "${file}" ]]; then
+			ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${file}"/*.mov -movflags faststart -pix_fmt yuv420p -c:v libx264 -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
 		fi
-		printf '\n%sdone. moving to next file.%s\n' "$biwhite" "$color_off"
+		printf '\n%sdone. moving to next file.%s\n' "${biwhite}" "${color_off}"
 		shift
 	done
 
diff --git a/makeconcat b/makeconcat
--- a/makeconcat
+++ b/makeconcat
@@ -11,13 +11,13 @@ today=$(date +"%Y%m%d")
 
 script_path=${0%/*}
 # script_path will be the directory path of {0} which is the script being called
-. "$script_path/nmaahcmmfunctions"
+. "${script_path}/nmaahcmmfunctions"
 # You can't directly call a function in another shell script.
 # You can move your function definitions into a separate file and then load them into your script using the . command, like this:
 # . /path/to/functions.sh
 # This will interpret functions.sh as if it's content were actually present in your file at this point.
 # This is a common mechanism for implementing shared libraries of shell functions.
-[[ -f "$script_path/nmaahcmmfunctions" ]] || { echo "Missing '$script_path/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 # will check to see that that nmaahcmmfunctions exists and if it doesn't (left side of || exits non-zero) then it will execute the right side of ||
 
 ### FUNCTIONS
@@ -26,26 +26,26 @@ makeconcat ()
 
 {
 	echo
-	printf "%sPlease enter the name of the concatenated file to be created.\n\t For example, SC_0001_20171211_Mangum_R8_01\nEnter file name:%s" "$biwhite" "$color_off"
+	printf "%sPlease enter the name of the concatenated file to be created.\n\t For example, SC_0001_20171211_Mangum_R8_01\nEnter file name:%s" "${biwhite}" "${color_off}"
 	read -r concatfile
 	## $concatfile will be the name of both the $txtfile and the outputed concatenated file. Name well.
 	echo
 	while [ "${*}" != "" ] ; do ## while the number of arguments is not zero do X
-		for file in "$1" ; do ## for the first argument do X
+		for file in "${1}" ; do ## for the first argument do X
 			suffix="${file##*.}" ## set $suffix to whatever the extension of your $file is
 			path="${file%/*}" ## the $path is set as the dirname of the first argument
-			txtfile="$path/$concatfile.txt" ## the $txtfile will be created in the same dir as the first agument and named after $concatfile
-			touch "$txtfile" ## the $txtfile is created, aka "touched"
-			printf "file '$file'\n" >> "$txtfile" ## the first arugment is written to $txtfile in the appropraite syntax for ffmpeg
+			txtfile="${path}/${concatfile}.txt" ## the $txtfile will be created in the same dir as the first agument and named after $concatfile
+			touch "${txtfile}" ## the $txtfile is created, aka "touched"
+			printf "file '${file}'\n" >> "${txtfile}" ## the first arugment is written to $txtfile in the appropraite syntax for ffmpeg
 			shift ## the script shifts from the first argument to the second argument. It will do this until there are no more arguments.
 		done
 	done
-	concatfile="$path/$concatfile.$suffix"
-	ffmpeg -f concat -safe 0 -i "$txtfile" -c copy "$concatfile" ## ffmpeg creates the concated file in the same directory as $files
+	concatfile="${path}/${concatfile}.$suffix"
+	ffmpeg -f concat -safe 0 -i "${txtfile}" -c copy "${concatfile}" ## ffmpeg creates the concated file in the same directory as $files
 	echo
 	cowsay "Done. Your concatenated video file is ready fo action." ## cowsay tells it like it is.
 	echo
-	printf "Your concatenated file is: %s" "$concatfile"
+	printf "Your concatenated file is: %s" "${concatfile}"
 
 }
 
diff --git a/moveDPX b/moveDPX
--- a/moveDPX
+++ b/moveDPX
@@ -17,62 +17,62 @@ moveDPX ()
 	while [ "${*}" != "" ] ; do
 
 		dpx_folder="${1}"
-		target="/Volumes/nmaahc-borndigital/06_DPX_checksums"
-		target_folder="/Volumes/nmaahc-borndigital/06_DPX_checksums/${dpx_folder##*/}"
+		{target}="/Volumes/nmaahc-borndigital/06_DPX_checksums"
+		{target}_folder="/Volumes/nmaahc-borndigital/06_DPX_checksums/${dpx_folder##*/}"
 		chmod_folder="/Volumes/nmaahc-borndigital/06_DPX_checksums"
 
-		if [ ! -d "$target" ] ; then
+		if [ ! -d "${target}" ] ; then
 			echo
-			printf "%s%s does not exist. Exiting." "$bired" "$target" >&2
+			printf "%s%s does not exist. Exiting." "${bired}" "${target}" >&2
 			exit
 		fi
 
-		if [ ! -d "$target_folder" ] ; then
+		if [ ! -d "${target_folder}" ] ; then
 			echo
-			printf "Creating:\t%s%s%s\n" "$biwhite" "$target_folder" "$color_off"
-			mkdir -p "$target_folder"
+			printf "Creating:\t%s%s%s\n" "${biwhite}" "${target_folder}" "${color_off}"
+			mkdir -p "${target_folder}"
 		fi
 
-		for file in "$dpx_folder"/*DPX*/* ; do
-			if [ -f "$target_folder"/*.dpx ] ; then
+		for file in "${dpx}_folder"/*DPX*/* ; do
+			if [ -f "${target_folder}"/*.dpx ] ; then
 				echo
-				printf "%s%s%s exists, verifying checksum.\n" "$biwhite" "${file##*/}" "$color_off"
-				rsync -avPhic "$file" "$target_folder"
+				printf "%s%s%s exists, verifying checksum.\n" "${biwhite}" "${file##*/}" "${color_off}"
+				rsync -avPhic "${file}" "${target_folder}"
 				rsync_err_1="$?"
 			else
-				rsync -avPhi "$file" "$target_folder"
+				rsync -avPhi "${file}" "${target_folder}"
 				rsync_err_1="$?"
 			fi
-			printf "%srsync exit status is: %s%s\n" "$biwhite" "$rsync_err_1" "$color_off"
+			printf "%srsync exit status is: %s%s\n" "${biwhite}" "${rsync_err_1}" "${color_off}"
 
-			if [[ "$rsync_err_1" == 0 ]]; then
+			if [[ "${rsync_err_1}" == 0 ]]; then
 				echo
-				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "$biwhite" "${file##*/}" "$color_off" "$biwhite" "$target_folder" "$color_off"
+				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${biwhite}" "${file##*/}" "${color_off}" "${biwhite}" "${target_folder}" "${color_off}"
 			  echo
 		 	else
-				printf "%sERRORS%s\n" "$bired" "$color_off" >&2
+				printf "%sERRORS%s\n" "${bired}" "${color_off}" >&2
 			fi
 			break 1
 		done
 
-		for md5 in "$dpx_folder"/*.md5 ; do
-			if [ -f "$target_folder"/*.md5 ] ; then
+		for md5 in "${dpx}_folder"/*.md5 ; do
+			if [ -f "${target_folder}"/*.md5 ] ; then
 				echo
-				printf "%s%s%s exists, verifying checksum.\n" "$biwhite" "${md5##*/}" "$color_off"
-				rsync -avPhic "$md5" "$target_folder"
+				printf "%s%s%s exists, verifying checksum.\n" "${biwhite}" "${md5##*/}" "${color_off}"
+				rsync -avPhic "${md5}" "${target_folder}"
 				rsync_err_2="$?"
 			else
-				rsync -avPhi "$md5" "$target_folder"
+				rsync -avPhi "${md5}" "${target_folder}"
 				rsync_err_2="$?"
 			fi
-				printf "%srsync exit status is: %s%s\n" "$biwhite" "$rsync_err_2" "$color_off"
+				printf "%srsync exit status is: %s%s\n" "${biwhite}" "${rsync_err_2}" "${color_off}"
 
-		 	if [[ "$rsync_err_2" == 0 ]] ; then
+		 	if [[ "${rsync_err_2}" == 0 ]] ; then
 				echo
-				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "$biwhite" "${md5##*/}" "$color_off" "$biwhite" "$target_folder" "$color_off"
+				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${biwhite}" "${md5##*/}" "${color_off}" "${biwhite}" "${target_folder}" "${color_off}"
 				echo
 			else
-				printf "%sERRORS\n" "$bired" "$color_off" >&2
+				printf "%sERRORS\n" "${bired}" "${color_off}" >&2
 			fi
 		done
 		printf "moving on\n"
@@ -81,8 +81,8 @@ moveDPX ()
 
 	done
 	echo
-	printf "%schanged permissions on the following files in directory %s to 777:%s\n" "$biwhite" "${chmod_folder##*/}" "$color_off"
-	chmod -vR 777 "$chmod_folder"
+	printf "%schanged permissions on the following files in directory %s to 777:%s\n" "${biwhite}" "${chmod_folder##*/}" "${color_off}"
+	chmod -vR 777 "${chmod_folder}"
 }
 
 #call the function(s)
diff --git a/restructureDPX b/restructureDPX
--- a/restructureDPX
+++ b/restructureDPX
@@ -18,306 +18,307 @@ color_off=$(tput sgr0)
 restructureDPX ()
 
 {
-printf "%sPlease enter the number of reels your DPX package has: %s" "$biwhite" "$color_off"
+printf "%sPlease enter the number of reels your DPX package has: %s" "${biwhite}" "${color_off}"
 read -r reelnumber
 echo
-printf '%sPlease enter DPX Object ID Number with underscores:\n' "$biwhite"
-printf 'ex. 2015_167_10_1\n%s' "$color_off"
+printf '%sPlease enter DPX Object ID Number with underscores:\n' "${biwhite}"
+printf 'ex. 2015_167_10_1\n%s' "${color_off}"
 read -r dpxid
 echo
-printf '%sPlease enter DPX Object title with underscores:\n' "$biwhite"
-printf 'ex. Juke_Joint\n%s' "$color_off"
+printf '%sPlease enter DPX Object title with underscores:\n' "${biwhite}"
+printf 'ex. Juke_Joint\n%s' "${color_off}"
 read -r title
 echo
-printf '%sPlease enter destination for directory tree to be created:\n%s' "$biwhite" "$color_off"
+printf '%sPlease enter destination for directory tree to be created:\n%s' "${biwhite}" "${color_off}"
 read -r dest
 echo
-printf '%sPlease enter directory to be worked with:\n%s' "$biwhite" "$color_off"
+printf '%sPlease enter directory to be worked with:\n%s' "${biwhite}" "${color_off}"
 read -r input
 
-case "$reelnumber" in
+case "${reelnumber}" in
 	1 )
 	#make $destination directory inside of $dest ex. 2012_79_1_54__Something_to_Build_On
 	echo
-	destination=("$dest"/"$dpxid"__"$title")
-	mkdir "$destination"
+	destination=("$dest"/"${dpxid}"__"${title}")
+	mkdir "${destination}"
 
 	echo
-	printf "%sMoving files from %s $input\n" "$biwhite" "$color_off"
+	printf "%sMoving files from %s ${input}\n" "${biwhite}" "${color_off}"
 	#find and move any .wav files fom $input to $destination
-	if [[ -d "$destination" ]] ; then
-		for wav in "$input"/*WAV ; do
-			if [[ ! -d "$wav" ]] ; then
-				printf "\n\t%sNo .wav directory found.%s\n" "$biwhite" "$color_off"
+	if [[ -d "${destination}" ]] ; then
+		for wav in "${input}"/*WAV ; do
+			if [[ ! -d "${wav}" ]] ; then
+				printf "\n\t%sNo .wav directory found.%s\n" "${biwhite}" "${color_off}"
 				echo
 			else
-				while [[ -d "$wav" ]] ; do
-					aud=("$destination"/"$dpxid"__"$title"__Audio) &&
-					printf "\n\t%sFound .wav directory.\n\tRenaming to:\n\t%s%s\n" "$biwhite" "$aud" "$color_off" &&
-					find "$input" -type d -name "*WAV" -exec mv -i "{}" "$destination"/"$dpxid"__"$title"__Audio \;
+				while [[ -d "${wav}" ]] ; do
+					aud=("${destination}"/"${dpxid}"__"${title}"__Audio) &&
+					printf "\n\t%sFound .wav directory.\n\tRenaming to:\n\t%s%s\n" "${biwhite}" "${aud}" "${color_off}" &&
+					find "${input}" -type d -name "*WAV" -exec mv -i "{}" "${destination}"/"${dpxid}"__"${title}"__Audio \;
 					echo
 				done
 			fi
 		done
 	else
-		printf "%sMissing%s %s" "$bired" "$color_off" "$destination"
+		printf "%sMissing%s %s" "${bired}" "${color_off}" "${destination}"
 		echo
 		exit 1
 	fi
 	#find and move and .mov files from $input to $destination
-		for mov in "$input"/*MOV ; do
+		for mov in "${input}"/*MOV ; do
 			if [[ ! -d "$mov" ]] ; then
-				printf "\n\t%sNo .mov directory found.%s\n" "$biwhite" "$color_off"
+				printf "\n\t%sNo .mov directory found.%s\n" "${biwhite}" "${color_off}"
 				echo
 			else
 				while [[ -d "$mov" ]] ; do
-					der=("$destination"/"$dpxid"__"$title"__Derivatives) &&
-					printf "\n\t%sFound .mov directory.\n\tRenaming to:\n\t%s%s\n" "$biwhite" "$der" "$color_off" &&
-					find "$input" -type d -name "*MOV" -exec mv -i "{}" "$destination"/"$dpxid"__"$title"__Derivatives \;
+					der=("${destination}"/"${dpxid}"__"${title}"__Derivatives) &&
+					printf "\n\t%sFound .mov directory.\n\tRenaming to:\n\t%s%s\n" "${biwhite}" "${der}" "${color_off}" &&
+					find "${input}" -type d -name "*MOV" -exec mv -i "{}" "${destination}"/"${dpxid}"__"${title}"__Derivatives \;
 					echo
 				done
 			fi
 		done
 	#move DPX directory from $input to $destination and rename
-		for dpx in "$input"/*DPX ; do
-			if [[ ! -d "$dpx" ]] ; then
-				printf "\n\t%sNo DPX directory found.%s\n" "$biwhite" "$color_off"
+		for dpx in "${input}"/*DPX ; do
+			if [[ ! -d "${dpx}" ]] ; then
+				printf "\n\t%sNo DPX directory found.%s\n" "${biwhite}" "${color_off}"
 				echo
 			else
-				while [[ -d "$dpx" ]] ; do
-					dpxdir=("$destination"/"$dpxid"__"$title"__DPX) &&
-					printf "\n\t%sFound DPX directory.\n\tRenaming to:\n\t%s%s\n" "$biwhite" "$dpxdir" "$color_off" &&
-					find "$input" -type d -name "*DPX" -exec mv -i {} "$destination"/"$dpxid"__"$title"__DPX \;
+				while [[ -d "${dpx}" ]] ; do
+					dpxdir=("${destination}"/"${dpxid}"__"${title}"__DPX) &&
+					printf "\n\t%sFound DPX directory.\n\tRenaming to:\n\t%s%s\n" "${biwhite}" "${dpx}dir" "${color_off}" &&
+					find "${input}" -type d -name "*DPX" -exec mv -i {} "${destination}"/"${dpxid}"__"${title}"__DPX \;
 					echo
 				done
 			fi
 		done
 	echo
 	#find the .wav and .mov files and rename them according to NMAAHC naming structures
-	printf "%sRenaming files in %s%s\n" "$biwhite" "$color_off" "$destination"
+	printf "%sRenaming files in %s%s\n" "${biwhite}" "${color_off}" "${destination}"
 	echo
-	if [[ -d "$aud" ]] ; then
-		find "$aud" -name "*.wav" -exec mv -i "{}" "$aud"/"$dpxid"_AUD.wav \;
-		wav="$aud"/"$dpxid"_AUD.wav
-		printf "\n\t%sRenamed audio file to %s%s\n" "$biwhite" "$wav" "$color_off"
+	if [[ -d "${aud}" ]] ; then
+		find "${aud}" -name "*.wav" -exec mv -i "{}" "${aud}"/"${dpxid}"_AUD.wav \;
+		wav="${aud}"/"${dpxid}"_AUD.wav
+		printf "\n\t%sRenamed audio file to %s%s\n" "${biwhite}" "${wav}" "${color_off}"
 	fi
-	if [[ -d "$der" ]] ; then
-		find "$der" -name "*ProRes*.mov" -exec mv -i "{}" "$der"/"$dpxid"_DER_01.mov \;
-		der1="$der"/"$dpxid"_DER_01.mov
-		printf "\n\t%sRenamed ProRes file to %s%s\n" "$biwhite" "$der1" "$color_off"
+	if [[ -d "${der}" ]] ; then
+		find "${der}" -name "*ProRes*.mov" -exec mv -i "{}" "${der}"/"${dpxid}"_DER_01.mov \;
+		der1="${der}"/"${dpxid}"_DER_01.mov
+		printf "\n\t%sRenamed ProRes file to %s%s\n" "${biwhite}" "${der1}" "${color_off}"
 		fi
-	if [[ -d "$der" ]] ; then
-		find "$der" -name "*Uncompressed.mov" -exec mv -i "{}" "$der"/"$dpxid"_DER_02.mov \;
-		der2="$der"/"$dpxid"_DER_02.mov
-		printf "\n\t%sRenamed uncompressed file to %s%s\n" "$biwhite" "$der2" "$color_off"
+	if [[ -d "${der}" ]] ; then
+		find "${der}" -name "*Uncompressed.mov" -exec mv -i "{}" "${der}"/"${dpxid}"_DER_02.mov \;
+		der2="${der}"/"${dpxid}"_DER_02.mov
+		printf "\n\t%sRenamed uncompressed file to %s%s\n" "${biwhite}" "${der2}" "${color_off}"
 		echo
 	fi
+	#remove the ${input} directory
 	#remove the $input directory
-	printf "%sRemoving:\n\t%s%s\n" "$biwhite" "$color_off" "$input"
-	rm -vri "$input"
+	printf "%sRemoving:\n\t%s%s\n" "${biwhite}" "${color_off}" "${input}"
+	rm -vri "${input}"
 	;;
 
 	2 )
-	destination=("$dest"/"$dpxid"__"$title")
-	mkdir "$destination"
+	destination=("$dest"/"${dpxid}"__"${title}")
+	mkdir "${destination}"
 
-	R1=("$destination"/"$dpxid"__"$title"_R1/"$dpxid"__"$title"_R1)
-	mkdir -p "$R1"
+	R1=("${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1)
+	mkdir -p "${R1}"
 
-	audR1="$R1"__Audio
-	mkdir -p "$audR1"
+	audR1="${R1}"__Audio
+	mkdir -p "${audR1}"
 
-	derR1="$R1"__Derivatives
-	mkdir -p "$derR1"
+	derR1="${R1}"__Derivatives
+	mkdir -p "${derR1}"
 
-	dpxR1="$R1"__DPX
-	mkdir -p "$dpxR1"
+	dpxR1="${R1}"__DPX
+	mkdir -p "${dpxR1}"
 
-	R2=("$destination"/"$dpxid"__"$title"_R2/"$dpxid"__"$title"_R2)
-	mkdir -p "$R2"
+	R2=("${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2)
+	mkdir -p "${R2}"
 
-	audR2="$R2"__Audio
-	mkdir -p "$audR2"
+	audR2="${R2}"__Audio
+	mkdir -p "${audR2}"
 
-	derR2="$R2"__Derivatives
-	mkdir -p "$derR2"
+	derR2="${R2}"__Derivatives
+	mkdir -p "${derR2}"
 
-	dpxR2="$R2"__DPX
-	mkdir -p "$dpxR2"
+	dpxR2="${R2}"__DPX
+	mkdir -p "${dpxR2}"
 	echo
-	printf "%sMoving files from%s %s" "$biwhite" "$color_off" "$input"
+	printf "%sMoving files from%s %s" "${biwhite}" "${color_off}" "${input}"
 
-	if [ -d "$audR1" ] ; then
-		find "$input" -name "*R1*.wav" -exec mv -vi {} "$audR1" \;
+	if [ -d "${audR1}" ] ; then
+		find "${input}" -name "*R1*.wav" -exec mv -vi {} "${audR1}" \;
 	else
-		printf "%sMissing $audR1%s" "$bired" "$color_off"
+		printf "%sMissing ${audR1}%s" "${bired}" "${color_off}"
 		exit 1
 	fi
-	if [ -d "$derR1" ] ; then
-		find "$input" -name "*R1*.mov" -exec mv -vi {} "$derR1" \;
+	if [ -d "${derR1}" ] ; then
+		find "${input}" -name "*R1*.mov" -exec mv -vi {} "${derR1}" \;
 	else
-		printf "%sMissing $derR1%s" "$bired" "$color_off"
+		printf "%sMissing ${derR1}%s" "${bired}" "${color_off}"
 		exit 1
 	fi
-	if [ -d "$dpxR1" ] ; then
-		find "$input" -name "*R1*.dpx" -exec mv -vi {} "$dpxR1" \;
+	if [ -d "${dpxR1}" ] ; then
+		find "${input}" -name "*R1*.dpx" -exec mv -vi {} "${dpxR1}" \;
 	else
-		printf "%sMissing $dpxR1%s" "$bired" "$color_off"
-		exit 1
-	fi
-
-	if [ -d "$audR2" ] ; then
-		find "$input" -name "*R2*.wav" -exec mv -vi {} "$audR2" \;
-	else
-		printf "%sMissing $audR2%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$derR2" ] ; then
-		find "$input" -name "*R2*.mov" -exec mv -vi {} "$derR2" \;
-	else
-		printf "%sMissing $derR2%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$dpxR2" ] ; then
-		find "$input" -name "*R2*.dpx" -exec mv -vi {} "$dpxR2" \;
-	else
-		printf "%sMissing $dpxR2%s" "$bired" "$color_off"
+		printf "%sMissing ${dpxR1}%s" "${bired}" "${color_off}"
 		exit 1
 	fi
 
-	echo
-	printf "%sReaming files in %s%s\n" "$biwhite" "$color_off" "$destination"
-	find "$audR1" -name "*R1*.wav" -exec mv -vi {} "$audR1"/"$dpxid"_R1_AUD.wav \;
-	find "$derR1" -name "*R1*ProRes*.mov" -exec mv -vi {} "$derR1"/"$dpxid"_R1_DER_01.mov \;
-	find "$derR1" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "$derR1"/"$dpxid"_R1_DER_02.mov \;
-	find "$audR2" -name "*R2*.wav" -exec mv -vi {} "$audR2"/"$dpxid"_R2_AUD.wav \;
-	find "$derR2" -name "*R2*ProRes*.mov" -exec mv -vi {} "$derR2"/"$dpxid"_R2_DER_01.mov \;
-	find "$derR2" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "$derR2"/"$dpxid"_R2_DER_02.mov \;
+	if [ -d "${audR2}" ] ; then
+		find "${input}" -name "*R2*.wav" -exec mv -vi {} "${audR2}" \;
+	else
+		printf "%sMissing ${audR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${derR2}" ] ; then
+		find "${input}" -name "*R2*.mov" -exec mv -vi {} "${derR2}" \;
+	else
+		printf "%sMissing ${derR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${dpxR2}" ] ; then
+		find "${input}" -name "*R2*.dpx" -exec mv -vi {} "${dpxR2}" \;
+	else
+		printf "%sMissing ${dpxR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
 
 	echo
-	printf "%sRemoving %s\n" "$biwhite" "$color_off" "$input"
-	rm -vri "$input"
+	printf "%sReaming files in %s%s\n" "${biwhite}" "${color_off}" "${destination}"
+	find "${audR1}" -name "*R1*.wav" -exec mv -vi {} "${audR1}"/"${dpxid}"_R1_AUD.wav \;
+	find "${derR1}" -name "*R1*ProRes*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_01.mov \;
+	find "${derR1}" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_02.mov \;
+	find "${audR2}" -name "*R2*.wav" -exec mv -vi {} "${audR2}"/"${dpxid}"_R2_AUD.wav \;
+	find "${derR2}" -name "*R2*ProRes*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_01.mov \;
+	find "${derR2}" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_02.mov \;
+
+	echo
+	printf "%sRemoving %s\n" "${biwhite}" "${color_off}" "${input}"
+	rm -vri "${input}"
 	;;
 
 	3 )
-	destination=("$dest"/"$dpxid"__"$title")
-	mkdir "$destination"
+	destination=("$dest"/"${dpxid}"__"${title}")
+	mkdir "${destination}"
 
-	R1=("$destination"/"$dpxid"__"$title"_R1/"$dpxid"__"$title"_R1)
-	mkdir -p "$R1"
+	R1=("${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1)
+	mkdir -p "${R1}"
 
-	audR1="$R1"__Audio
-	mkdir -p "$audR1"
+	audR1="${R1}"__Audio
+	mkdir -p "${audR1}"
 
-	derR1="$R1"__Derivatives
-	mkdir -p "$derR1"
+	derR1="${R1}"__Derivatives
+	mkdir -p "${derR1}"
 
-	dpxR1="$R1"__DPX
-	mkdir -p "$dpxR1"
+	dpxR1="${R1}"__DPX
+	mkdir -p "${dpxR1}"
 
-	R2=("$destination"/"$dpxid"__"$title"_R2/"$dpxid"__"$title"_R2)
-	mkdir -p "$R2"
+	R2=("${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2)
+	mkdir -p "${R2}"
 
-	audR2="$R2"__Audio
-	mkdir -p "$audR2"
+	audR2="${R2}"__Audio
+	mkdir -p "${audR2}"
 
-	derR2="$R2"__Derivatives
-	mkdir -p "$derR2"
+	derR2="${R2}"__Derivatives
+	mkdir -p "${derR2}"
 
-	dpxR2="$R2"__DPX
-	mkdir -p "$dpxR2"
+	dpxR2="${R2}"__DPX
+	mkdir -p "${dpxR2}"
 
-	R3=("$destination"/"$dpxid"__"$title"_R3/"$dpxid"__"$title"_R3)
-	mkdir -p "$R3"
+	R3=("${destination}"/"${dpxid}"__"${title}"_R3/"${dpxid}"__"${title}"_R3)
+	mkdir -p "${R3}"
 
-	audR3="$R3"__Audio
-	mkdir -p "$audR3"
+	audR3="${R3}"__Audio
+	mkdir -p "${audR3}"
 
-	derR3="$R3"__Derivatives
-	mkdir -p "$derR3"
+	derR3="${R3}"__Derivatives
+	mkdir -p "${derR3}"
 
-	dpxR3="$R3"__DPX
-	mkdir -p "$dpxR3"
-
-	echo
-	printf "%sMoving files from%s %s" "$biwhite" "$color_off" "$input"
-
-	if [ -d "$audR1" ] ; then
-		find "$input" -name "*R1*.wav" -exec mv -vi {} "$audR1" \;
-	else
-		printf "%sMissing $audR1%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$derR1" ] ; then
-		find "$input" -name "*R1*.mov" -exec mv -vi {} "$derR1" \;
-	else
-		printf "%sMissing $derR1%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$dpxR1" ] ; then
-		find "$input" -name "*R1*.dpx" -exec mv -vi {} "$dpxR1" \;
-	else
-		printf "%sMissing $dpxR1%s" "$bired" "$color_off"
-		exit 1
-	fi
-
-	if [ -d "$audR2" ] ; then
-		find "$input" -name "*R2*.wav" -exec mv -vi {} "$audR2" \;
-	else
-		printf "%sMissing $audR2%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$derR2" ] ; then
-		find "$input" -name "*R2*.mov" -exec mv -vi {} "$derR2" \;
-	else
-		printf "%sMissing $derR2%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$dpxR2" ] ; then
-		find "$input" -name "*R2*.dpx" -exec mv -vi {} "$dpxR2" \;
-	else
-		printf "%sMissing $dpxR2%s" "$bired" "$color_off"
-		exit 1
-	fi
-
-	if [ -d "$audR3" ] ; then
-		find "$input" -name "*R3*.wav" -exec mv -vi {} "$audR3" \;
-	else
-		printf "%sMissing $audR3%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$derR3" ] ; then
-		find "$input" -name "*R3*.mov" -exec mv -vi {} "$derR3" \;
-	else
-		printf "%sMissing $derR3%s" "$bired" "$color_off"
-		exit 1
-	fi
-	if [ -d "$dpxR3" ] ; then
-		find "$input" -name "*R3*.dpx" -exec mv -vi {} "$dpxR3" \;
-	else
-		printf "%sMissing $dpxR3%s" "$bired" "$color_off"
-		exit 1
-	fi
+	dpxR3="${R3}"__DPX
+	mkdir -p "${dpxR3}"
 
 	echo
-	printf "%sReaming files in %s%s\n" "$biwhite" "$color_off" "$destination"
-	find "$audR1" -name "*R1*.wav" -exec mv -vi {} "$audR1"/"$dpxid"_R1_AUD.wav \;
-	find "$derR1" -name "*R1*ProRes*.mov" -exec mv -vi {} "$derR1"/"$dpxid"_R1_DER_01.mov \;
-	find "$derR1" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "$derR1"/"$dpxid"_R1_DER_02.mov \;
-	find "$audR2" -name "*R2*.wav" -exec mv -vi {} "$audR2"/"$dpxid"_R2_AUD.wav \;
-	find "$derR2" -name "*R2*ProRes*.mov" -exec mv -vi {} "$derR2"/"$dpxid"_R2_DER_01.mov \;
-	find "$derR2" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "$derR2"/"$dpxid"_R2_DER_02.mov \;
-	find "$audR3" -name "*R3*.wav" -exec mv -vi {} "$audR3"/"$dpxid"_R3_AUD.wav \;
-	find "$derR3" -name "*R3*ProRes*.mov" -exec mv -vi {} "$derR3"/"$dpxid"_R3_DER_01.mov \;
-	find "$derR3" -name "*R3*Uncompressed*.mov" -exec mv -vi {} "$derR3"/"$dpxid"_R3_DER_02.mov \;
+	printf "%sMoving files from%s %s" "${biwhite}" "${color_off}" "${input}"
+
+	if [ -d "${audR1}" ] ; then
+		find "${input}" -name "*R1*.wav" -exec mv -vi {} "${audR1}" \;
+	else
+		printf "%sMissing ${audR1}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${derR1}" ] ; then
+		find "${input}" -name "*R1*.mov" -exec mv -vi {} "${derR1}" \;
+	else
+		printf "%sMissing ${derR1}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${dpxR1}" ] ; then
+		find "${input}" -name "*R1*.dpx" -exec mv -vi {} "${dpxR1}" \;
+	else
+		printf "%sMissing ${dpxR1}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+
+	if [ -d "${audR2}" ] ; then
+		find "${input}" -name "*R2*.wav" -exec mv -vi {} "${audR2}" \;
+	else
+		printf "%sMissing ${audR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${derR2}" ] ; then
+		find "${input}" -name "*R2*.mov" -exec mv -vi {} "${derR2}" \;
+	else
+		printf "%sMissing ${derR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${dpxR2}" ] ; then
+		find "${input}" -name "*R2*.dpx" -exec mv -vi {} "${dpxR2}" \;
+	else
+		printf "%sMissing ${dpxR2}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+
+	if [ -d "${audR3}" ] ; then
+		find "${input}" -name "*R3*.wav" -exec mv -vi {} "${audR3}" \;
+	else
+		printf "%sMissing ${audR3}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${derR3}" ] ; then
+		find "${input}" -name "*R3*.mov" -exec mv -vi {} "${derR3}" \;
+	else
+		printf "%sMissing ${derR3}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
+	if [ -d "${dpxR3}" ] ; then
+		find "${input}" -name "*R3*.dpx" -exec mv -vi {} "${dpxR3}" \;
+	else
+		printf "%sMissing ${dpxR3}%s" "${bired}" "${color_off}"
+		exit 1
+	fi
 
 	echo
-	printf "%sRemoving \n" "$biwhite" "$color_off" "$input"
-	rm -vri "$input"
+	printf "%sReaming files in %s%s\n" "${biwhite}" "${color_off}" "${destination}"
+	find "${audR1}" -name "*R1*.wav" -exec mv -vi {} "${audR1}"/"${dpxid}"_R1_AUD.wav \;
+	find "${derR1}" -name "*R1*ProRes*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_01.mov \;
+	find "${derR1}" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_02.mov \;
+	find "${audR2}" -name "*R2*.wav" -exec mv -vi {} "${audR2}"/"${dpxid}"_R2_AUD.wav \;
+	find "${derR2}" -name "*R2*ProRes*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_01.mov \;
+	find "${derR2}" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_02.mov \;
+	find "${audR3}" -name "*R3*.wav" -exec mv -vi {} "${audR3}"/"${dpxid}"_R3_AUD.wav \;
+	find "${derR3}" -name "*R3*ProRes*.mov" -exec mv -vi {} "${derR3}"/"${dpxid}"_R3_DER_01.mov \;
+	find "${derR3}" -name "*R3*Uncompressed*.mov" -exec mv -vi {} "${derR3}"/"${dpxid}"_R3_DER_02.mov \;
+
+	echo
+	printf "%sRemoving \n" "${biwhite}" "${color_off}" "${input}"
+	rm -vri "${input}"
 	;;
 
 	*	)
-	printf '%sERROR. Presently, this script can only handle DPX packages of 1 or 2 or 3 reels. Check back later.' "$bired"
+	printf '%sERROR. Presently, this script can only handle DPX packages of 1 or 2 or 3 reels. Check back later.' "${bired}"
 	echo
 	cowsay 'SORRY!'
 	;;
