move script initialization steps to beginning
this fixes the usage function which was listing dependencies as empty

diff --git a/camera_cards b/camera_cards
--- a/camera_cards
+++ b/camera_cards
@@ -2,6 +2,19 @@
 
 # a script to turn raw camera cards into SIPs
 
+# load nmaahcmmfunctions into this script
+SCRIPT_PATH="${0%/*}"
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+_initialize_make # safe script termination process defined in nmaahcmmfunctions
+# set script variables
+DEPENDENCIES=(ffmpeg md5sum tree)
+OP="${USER}"
+AIP="YES"
+TAR="NO"
+LOG="${LOGDIR%/}/$(basename "${0}")_$(date +%F-%H%M%S).log"
+REQUIRECONFIG="N"
+
 # define functions
 _generate_metadata(){
     _report -g "Generating metadata reports..."
@@ -65,19 +78,6 @@ while getopts ":m:o:ctah" OPT; do
     esac
 done
 shift $(( ${OPTIND} - 1 ))
-
-# load nmaahcmmfunctions into this script
-SCRIPT_PATH="${0%/*}"
-. "${SCRIPT_PATH}/nmaahcmmfunctions"
-[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
-_initialize_make # safe script termination process defined in nmaahcmmfunctions
-# set script variables
-DEPENDENCIES=(ffmpeg md5sum tree)
-OP="${USER}"
-AIP="YES"
-TAR="NO"
-LOG="${LOGDIR%/}/$(basename "${0}")_$(date +%F-%H%M%S).log"
-REQUIRECONFIG="N"
 
 # check for unassigned variables
 CAMERA_CARD_DIR="${1}"
