indents after previous

diff --git a/camera_cards b/camera_cards
--- a/camera_cards
+++ b/camera_cards
@@ -497,7 +497,7 @@ START_TIME="$(date +%FT%T)"
 if [[ "${SINGLE_OUTPUT}" = "Y" ]] ; then
     AIPDIR="${AIP_DESTINATION}"
 else
-AIPDIR="${AIP_DESTINATION}/${MEDIAID}"
+    AIPDIR="${AIP_DESTINATION}/${MEDIAID}"
 fi
 if [[ "${SINGLE_OUTPUT}" = "Y" ]] ; then
     AIPDIR_AIP="${AIPDIR}"
@@ -507,51 +507,51 @@ if [[ "${SINGLE_OUTPUT}" = "Y" ]] ; then
     METADATA_ORIGINAL_CAMERA_FILES_DIR="${METADATADIR}"
     mkdir -p "${AIPDIR_AIP}"
 else
-METADATADIR="${AIPDIR}/metadata"
-LOG="${METADATADIR}/$(basename "${0}")_$(date +%F-%H%M%S).log"
-METADATA_REPORTS_DIR="${METADATADIR}/reports"
-METADATA_ORIGINAL_CAMERA_FILES_DIR="${METADATADIR}/original_camera_files"
-if [[ -d "${AIPDIR}" ]] ; then
-    _report -rt "ERROR: Output directory ${AIPDIR} already exists! Exiting to avoid overwriting..."
-    exit 1
-fi
-if [[ "${AIP}" == "YES" && "${TAR}" == "YES" ]] ; then
-    AIPDIR_AIP="${AIPDIR}/objects/AIP"
-    AIPDIR_TAR="${AIPDIR}/objects/TAR"
-    mkdir -p "${METADATA_REPORTS_DIR}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" "${AIPDIR_AIP}" "${AIPDIR_TAR}"
-elif [[ "${AIP}" == "YES" ]] ; then
-    AIPDIR_AIP="${AIPDIR}/objects"
-    mkdir -p "${METADATA_REPORTS_DIR}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" "${AIPDIR_AIP}"
-elif [[ "${TAR}" == "YES" ]] ; then
-    AIPDIR_TAR="${AIPDIR}/objects/TAR"
-    mkdir -p "${METADATA_REPORTS_DIR}" "${AIPDIR_TAR}"
-else
-    _report -r "ERROR: camera_cards needs to produce either an AIP or TAR output."
-    exit 1
-fi
+    METADATADIR="${AIPDIR}/metadata"
+    LOG="${METADATADIR}/$(basename "${0}")_$(date +%F-%H%M%S).log"
+    METADATA_REPORTS_DIR="${METADATADIR}/reports"
+    METADATA_ORIGINAL_CAMERA_FILES_DIR="${METADATADIR}/original_camera_files"
+    if [[ -d "${AIPDIR}" ]] ; then
+        _report -rt "ERROR: Output directory ${AIPDIR} already exists! Exiting to avoid overwriting..."
+        exit 1
+    fi
+    if [[ "${AIP}" == "YES" && "${TAR}" == "YES" ]] ; then
+        AIPDIR_AIP="${AIPDIR}/objects/AIP"
+        AIPDIR_TAR="${AIPDIR}/objects/TAR"
+        mkdir -p "${METADATA_REPORTS_DIR}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" "${AIPDIR_AIP}" "${AIPDIR_TAR}"
+    elif [[ "${AIP}" == "YES" ]] ; then
+        AIPDIR_AIP="${AIPDIR}/objects"
+        mkdir -p "${METADATA_REPORTS_DIR}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" "${AIPDIR_AIP}"
+    elif [[ "${TAR}" == "YES" ]] ; then
+        AIPDIR_TAR="${AIPDIR}/objects/TAR"
+        mkdir -p "${METADATA_REPORTS_DIR}" "${AIPDIR_TAR}"
+    else
+        _report -r "ERROR: camera_cards needs to produce either an AIP or TAR output."
+        exit 1
+    fi
 fi
 ### procedure for creating structured AIPs (concatenating video files and restructuring metadata directories)
 if [[ "${AIP}" == "YES" ]] ; then
     if [[ "${SINGLE_OUTPUT}" != "Y" ]] ; then
-    mkdir -p "${METADATA_ORIGINAL_CAMERA_FILES_DIR}"
-    # copy selected original metadata files to AIP
-    _report -g "Moving significant camera-generated metadata files to AIP..."
-    CAMERA_CARD_METADATA2KEEP=()
-    while read METADATA_FILE ; do
-        CAMERA_CARD_METADATA2KEEP+=("${METADATA_FILE}")
-    done < <(_read_inventory -r "${CLIP_SELECTION}" -f ",metadata," "FILE_NAME")
-    if [[ -w "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" ]] ; then
-        if (( ${#CAMERA_CARD_METADATA2KEEP[@]} != 0 )) ; then
-            _report -g "Copying some camera metadata files into the package."
-            rsync -avh "${CAMERA_CARD_METADATA2KEEP[@]}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}"
+        mkdir -p "${METADATA_ORIGINAL_CAMERA_FILES_DIR}"
+        # copy selected original metadata files to AIP
+        _report -g "Moving significant camera-generated metadata files to AIP..."
+        CAMERA_CARD_METADATA2KEEP=()
+        while read METADATA_FILE ; do
+            CAMERA_CARD_METADATA2KEEP+=("${METADATA_FILE}")
+        done < <(_read_inventory -r "${CLIP_SELECTION}" -f ",metadata," "FILE_NAME")
+        if [[ -w "${METADATA_ORIGINAL_CAMERA_FILES_DIR}" ]] ; then
+            if (( ${#CAMERA_CARD_METADATA2KEEP[@]} != 0 )) ; then
+                _report -g "Copying some camera metadata files into the package."
+                rsync -avh "${CAMERA_CARD_METADATA2KEEP[@]}" "${METADATA_ORIGINAL_CAMERA_FILES_DIR}"
+            fi
+        else
+            _report -r "Error: the folder for camera metadata is not writable."
+            exit 1
         fi
-    else
-        _report -r "Error: the folder for camera metadata is not writable."
-        exit 1
-    fi
 
-    # generate metadata reports
-    _generate_metadata
+        # generate metadata reports
+        _generate_metadata
     fi
 
     ## concatenate video files into a single file
@@ -616,35 +616,37 @@ if [[ "${AIP}" == "YES" ]] ; then
     "${FFMPEG_PATH}" -f concat -safe 0 -i "${TEMP_CONCATLIST}" -i "${FIRST_FILE}" -map 0 -map_metadata 1 "${MIDDLE_OPTIONS_ALL[@]}" "${MIDDLE_OPTIONS[@]}" "${AUDIO_STRATEGY[@]}" "${CONCATENATED_VIDEO_FILE}"
     # calculate md5 for each stream in the file
     if [[ "${SINGLE_OUTPUT}" != "Y" ]] ; then
-    _report -b "Calculating streamhash and checking input for errors."
-    DECODER_LOG="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_decoder_log.txt"
-    STREAMHASH="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_streamhash.md5"
-    "${FFMPEG_PATH}" -debug_ts -f concat -safe 0 -i "${TEMP_CONCATLIST}" -map 0 -c copy -f streamhash -hash md5 "${MIDDLE_OPTIONS_ALL[@]}" "${STREAMHASH}" 2> "${DECODER_LOG}"
+        _report -b "Calculating streamhash and checking input for errors."
+        DECODER_LOG="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_decoder_log.txt"
+        STREAMHASH="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_streamhash.md5"
+        "${FFMPEG_PATH}" -debug_ts -f concat -safe 0 -i "${TEMP_CONCATLIST}" -map 0 -c copy -f streamhash -hash md5 "${MIDDLE_OPTIONS_ALL[@]}" "${STREAMHASH}" 2> "${DECODER_LOG}"
 
-    # decode error summary
-    FIRST_VIDEO_FILE="$(_read_inventory -f ",video," "FILE_NAME" | head -n 1)"
-    VIDEO_FORMAT="$(ffprobe -v 0 -i "${FIRST_VIDEO_FILE}" -show_entries format=format_name -of default=nw=1:nk=1)"
-    VIDEO_ENCODING="$(ffprobe -v 0 -i "${FIRST_VIDEO_FILE}" -select_streams v:0 -show_entries stream=codec_name -of default=nw=1:nk=1 | head -n 1)"
-    DEMUXER_ERROR_SUMMARY="$(grep -B 1 "^\[${VIDEO_FORMAT} @" "${DECODER_LOG}" | grep "^\[${VIDEO_FORMAT} @\|pts_time")"
-    DECODER_ERROR_SUMMARY="$(grep -B 1 "^\[${VIDEO_ENCODING} @" "${DECODER_LOG}" | grep "^\[${VIDEO_ENCODING} @\|pts_time")"
-    if [[ -n "${DECODER_ERROR_SUMMARY}" ]] ; then
-        DECODER_LOG_SUMMARY="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_decoder_log_summary.txt"
-        _report -r "Warning there's some decoding errors. If a timestamp is referenced here please review that portion of the output."
-        echo "${DECODER_ERROR_SUMMARY}"
-        echo "${DECODER_ERROR_SUMMARY}" > "${DECODER_LOG_SUMMARY}"
-    fi
-    if [[ -n "${DEMUXER_ERROR_SUMMARY}" ]] ; then
-        DEMUXER_LOG_SUMMARY="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_demuxer_log_summary.txt"
-        _report -r "Warning there's some demuxer errors. If a timestamp is referenced here please review that portion of the output."
-        echo "${DEMUXER_ERROR_SUMMARY}"
-        echo "${DEMUXER_ERROR_SUMMARY}" > "${DEMUXER_LOG_SUMMARY}"
-    fi
+        # decode error summary
+        FIRST_VIDEO_FILE="$(_read_inventory -f ",video," "FILE_NAME" | head -n 1)"
+        VIDEO_FORMAT="$(ffprobe -v 0 -i "${FIRST_VIDEO_FILE}" -show_entries format=format_name -of default=nw=1:nk=1)"
+        VIDEO_ENCODING="$(ffprobe -v 0 -i "${FIRST_VIDEO_FILE}" -select_streams v:0 -show_entries stream=codec_name -of default=nw=1:nk=1 | head -n 1)"
+        DEMUXER_ERROR_SUMMARY="$(grep -B 1 "^\[${VIDEO_FORMAT} @" "${DECODER_LOG}" | grep "^\[${VIDEO_FORMAT} @\|pts_time")"
+        DECODER_ERROR_SUMMARY="$(grep -B 1 "^\[${VIDEO_ENCODING} @" "${DECODER_LOG}" | grep "^\[${VIDEO_ENCODING} @\|pts_time")"
+        if [[ -n "${DECODER_ERROR_SUMMARY}" ]] ; then
+            DECODER_LOG_SUMMARY="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_decoder_log_summary.txt"
+            _report -r "Warning there's some decoding errors. If a timestamp is referenced here please review that portion of the output."
+            echo "${DECODER_ERROR_SUMMARY}"
+            echo "${DECODER_ERROR_SUMMARY}" > "${DECODER_LOG_SUMMARY}"
+        fi
+        if [[ -n "${DEMUXER_ERROR_SUMMARY}" ]] ; then
+            DEMUXER_LOG_SUMMARY="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}")_demuxer_log_summary.txt"
+            _report -r "Warning there's some demuxer errors. If a timestamp is referenced here please review that portion of the output."
+            echo "${DEMUXER_ERROR_SUMMARY}"
+            echo "${DEMUXER_ERROR_SUMMARY}" > "${DEMUXER_LOG_SUMMARY}"
+        fi
 
-    # tests for video file existing
-    FFMPEG_EXIT_CODE="${?}"
-    if [[ ! -s "${CONCATENATED_VIDEO_FILE}" ]] ; then ((FFMPEG_ERRORS++)) ; fi
-    _write_package_log "CONCATENATED VIDEO FILE" "${CONCATENATED_VIDEO_FILE}"
-    _report -g "Video concatenation process finished"
+        # tests for video file existing
+        FFMPEG_EXIT_CODE="${?}"
+        if [[ ! -s "${CONCATENATED_VIDEO_FILE}" ]] ; then
+            ((FFMPEG_ERRORS++))
+        fi
+        _write_package_log "CONCATENATED VIDEO FILE" "${CONCATENATED_VIDEO_FILE}"
+        _report -g "Video concatenation process finished"
     fi
 
     # if there are audio-only files, concatenate them and join with concatenated video file
@@ -677,32 +679,32 @@ if [[ "${AIP}" == "YES" ]] ; then
     fi
 
     if [[ "${SINGLE_OUTPUT}" != "Y" ]] ; then
-    # generate md5 of concatenated file
-    if [[ -f "${CONCATENATED_FILE_MERGED}" ]] ; then
-        CONCATENATED_MD5_OUTPUT="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_FILE_MERGED%.*}").md5"
-        md5sum "${CONCATENATED_FILE_MERGED}" > "${CONCATENATED_MD5_OUTPUT}"
-    else
-        CONCATENATED_MD5_OUTPUT="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}").md5"
-        md5sum "${CONCATENATED_VIDEO_FILE}" > "${CONCATENATED_MD5_OUTPUT}"
-    fi
-
-    if [[ "${CAMERA_CARD_TYPE}" == "GENERAL" ]] ; then
-        # general profile only: move all video files to AIP as separate files, in case concatenation does not work for this camera card structure
-        DUPLICATE_NAMES="$(while read FILE ; do basename "${FILE}" ; done < <(_read_inventory "FILE_NAME") | sort | uniq -d)"
-        if [[ -n "${DUPLICATE_NAMES}" ]] ; then # check for duplicate filenames on camera card before beginning transfer process
-            _report -r "Duplicate filenames found on original camera card! Not completing automated packaging process in order to avoid overwriting files with the same name. Please take a closer look at your original camera card's file structure to create this AIP."
-            _report -r "Also note that metadata files (in the nmaahc_metadata folder of your AIP) may not have been properly generated for all files with the same filename."
-            exit 1
+        # generate md5 of concatenated file
+        if [[ -f "${CONCATENATED_FILE_MERGED}" ]] ; then
+            CONCATENATED_MD5_OUTPUT="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_FILE_MERGED%.*}").md5"
+            md5sum "${CONCATENATED_FILE_MERGED}" > "${CONCATENATED_MD5_OUTPUT}"
         else
-            if [[ "${KEEP_ALL}" = "Y" ]] ; then
-                echo
-                _report -g "Moving original audiovisual files to AIP..."
-                while read FILE ; do
-                    rsync -avh --progress "${FILE}" "${AIPDIR_AIP}/"
-                done < <(_read_inventory -f ",video,\|,audio," "FILE_NAME")
+            CONCATENATED_MD5_OUTPUT="${METADATA_REPORTS_DIR}/$(basename "${CONCATENATED_VIDEO_FILE%.*}").md5"
+            md5sum "${CONCATENATED_VIDEO_FILE}" > "${CONCATENATED_MD5_OUTPUT}"
+        fi
+
+        if [[ "${CAMERA_CARD_TYPE}" == "GENERAL" ]] ; then
+            # general profile only: move all video files to AIP as separate files, in case concatenation does not work for this camera card structure
+            DUPLICATE_NAMES="$(while read FILE ; do basename "${FILE}" ; done < <(_read_inventory "FILE_NAME") | sort | uniq -d)"
+            if [[ -n "${DUPLICATE_NAMES}" ]] ; then # check for duplicate filenames on camera card before beginning transfer process
+                _report -r "Duplicate filenames found on original camera card! Not completing automated packaging process in order to avoid overwriting files with the same name. Please take a closer look at your original camera card's file structure to create this AIP."
+                _report -r "Also note that metadata files (in the nmaahc_metadata folder of your AIP) may not have been properly generated for all files with the same filename."
+                exit 1
+            else
+                if [[ "${KEEP_ALL}" = "Y" ]] ; then
+                    echo
+                    _report -g "Moving original audiovisual files to AIP..."
+                    while read FILE ; do
+                        rsync -avh --progress "${FILE}" "${AIPDIR_AIP}/"
+                    done < <(_read_inventory -f ",video,\|,audio," "FILE_NAME")
+                fi
             fi
         fi
-    fi
     fi
 fi
 
@@ -735,34 +737,34 @@ _write_package_log "START TIME" "${START_TIME}"
 # error reporting
 echo
 if [[ "${SINGLE_OUTPUT}" != "Y" ]] ; then
-if [[ ! -s "${TREE}" ]] ; then
-    _report -r "Metadata generation process created one or more blank files. ${TREE} may be empty. Review metadata output at ${METADATA_REPORTS_DIR}."
-    _write_package_log "POSSIBLE_ERROR_REVIEW" "Metadata generation process created one or more blank files"
-fi
-if [[ "${FFMPEG_EXIT_CODE}" -gt 0 ]] || [[ "${FFMPEG_ERRORS}" -gt 0 ]] ; then
-    _report -r "FFmpeg may have encountered errors - review terminal output for more detail."
-else
-    _report -g "FFmpeg exit codes look ok"
-    if [[ -s "${CONCATENATED_AUDIO_FILE}" ]] ; then
-        if [[ "${VIDEO_DURATION}" -ne "${AUDIO_DURATION}" ]] ; then
-        _report -r "Concatenated audio and video files were not the same length - review final merged file for sync at ${CONCATENATED_FILE_MERGED} (video duration = ${VIDEO_DURATION}, audio duration = ${AUDIO_DURATION})"
-        _write_package_log "POSSIBLE_ERROR_REVIEW" "Concatenated audio and video files were not the same length"
-        else
-            _report -g "Concatenated audio and video process looks ok"
+    if [[ ! -s "${TREE}" ]] ; then
+        _report -r "Metadata generation process created one or more blank files. ${TREE} may be empty. Review metadata output at ${METADATA_REPORTS_DIR}."
+        _write_package_log "POSSIBLE_ERROR_REVIEW" "Metadata generation process created one or more blank files"
+    fi
+    if [[ "${FFMPEG_EXIT_CODE}" -gt 0 ]] || [[ "${FFMPEG_ERRORS}" -gt 0 ]] ; then
+        _report -r "FFmpeg may have encountered errors - review terminal output for more detail."
+    else
+        _report -g "FFmpeg exit codes look ok"
+        if [[ -s "${CONCATENATED_AUDIO_FILE}" ]] ; then
+            if [[ "${VIDEO_DURATION}" -ne "${AUDIO_DURATION}" ]] ; then
+            _report -r "Concatenated audio and video files were not the same length - review final merged file for sync at ${CONCATENATED_FILE_MERGED} (video duration = ${VIDEO_DURATION}, audio duration = ${AUDIO_DURATION})"
+            _write_package_log "POSSIBLE_ERROR_REVIEW" "Concatenated audio and video files were not the same length"
+            else
+                _report -g "Concatenated audio and video process looks ok"
+            fi
+        fi
+        if [[ "${AIP}" == "YES" ]] ; then # check for losslessness of concatenated file by comparing bitstream md5s
+            OUTPUT_STREAMHASH="$(_maketemp)"
+            _report -b "Checking streamhash between input and output..."
+            "${FFMPEG_PATH}" -y -loglevel quiet -report -i "${CONCATENATED_VIDEO_FILE}" -map 0 -c copy -f streamhash -hash md5 "${MIDDLE_OPTIONS_ALL[@]}" "${OUTPUT_STREAMHASH}"
+            if [[ $(cat "${STREAMHASH}") != $(cat "${OUTPUT_STREAMHASH}") ]] ; then
+                _report -r "Concatenation process was not lossless! Review final merged file at ${CONCATENATED_VIDEO_FILE}"
+                _write_package_log "POSSIBLE_ERROR_REVIEW" "Concatenation process was not lossless based on bitstream md5s"
+            else
+                _report -g "Concatenated process looks lossless"
+            fi
         fi
     fi
-    if [[ "${AIP}" == "YES" ]] ; then # check for losslessness of concatenated file by comparing bitstream md5s
-        OUTPUT_STREAMHASH="$(_maketemp)"
-        _report -b "Checking streamhash between input and output..."
-        "${FFMPEG_PATH}" -y -loglevel quiet -report -i "${CONCATENATED_VIDEO_FILE}" -map 0 -c copy -f streamhash -hash md5 "${MIDDLE_OPTIONS_ALL[@]}" "${OUTPUT_STREAMHASH}"
-        if [[ $(cat "${STREAMHASH}") != $(cat "${OUTPUT_STREAMHASH}") ]] ; then
-            _report -r "Concatenation process was not lossless! Review final merged file at ${CONCATENATED_VIDEO_FILE}"
-            _write_package_log "POSSIBLE_ERROR_REVIEW" "Concatenation process was not lossless based on bitstream md5s"
-        else
-            _report -g "Concatenated process looks lossless"
-        fi
-    fi
-fi
 fi
 
 # log script ending
