move functions process after usage so help docs are accessible without configuration

diff --git a/camera_cards b/camera_cards
--- a/camera_cards
+++ b/camera_cards
@@ -4,9 +4,6 @@
 
 # load nmaahcmmfunctions into this script
 SCRIPT_PATH="${0%/*}"
-. "${SCRIPT_PATH}/nmaahcmmfunctions"
-[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
-_initialize_make # safe script termination process defined in nmaahcmmfunctions
 DEPENDENCIES=(ffmpeg md5sum)
 OP="${USER}"
 AIP="YES"
@@ -51,6 +48,10 @@ while getopts ":m:th" OPT; do
     esac
 done
 shift $(( ${OPTIND} - 1 ))
+
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+_initialize_make # safe script termination process defined in nmaahcmmfunctions
 
 # define functions
 _generate_metadata(){
