add _report function (deprecate printf colors)
-Add _report function from mmfunctions, which makes it simpler to color code user feedback and see that feedback plainly in the script.
-Deprecate printf colors.
-Deprecate %s notation and replaces "%s" with explicit variables (also in the aim of plainness and upkeep).
-Other changes in script feedback and maintenance: typo corrections (including changing variables from lowercase to uppercase); standardized log calls upon unexpected exits.

diff --git a/ingestfile b/ingestfile
--- a/ingestfile
+++ b/ingestfile
@@ -166,8 +166,8 @@ if [[ -z "${MEDIAID}" ]] && [[ "${PACKAGETYPE}" != "Digitized Film (DPX package)
     read -e MEDIAID
     [[ "${MEDIAID}" = "q" ]] && exit 0
     # validate id and perhaps fail with exit
-    [[ -z "${MEDIAID}" ]] && { printf "${BIRED}ERROR You must enter a valid MEDIA ID${COLOR_OFF}\n" ; exit ;};
-    [[ ! -z $(echo "${MEDIAID}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { printf "ERROR The MEDIA ID must only contain letters, numbers, hyphen and underscore\n" ; exit 1 ;};
+    [[ -z "${MEDIAID}" ]] && { _report -rt  "ERROR: You must enter a valid MEDIA ID" ; exit ;};
+    [[ ! -z $(echo "${MEDIAID}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { _report -rt  "ERROR The MEDIA ID must only contain letters, numbers, hyphen and underscore" ; exit 1 ;};
 fi
 if [[ -z "${PACKAGETYPE}" ]] ; then
     printf "Select a package type:"
@@ -191,11 +191,11 @@ if [[ "${PACKAGETYPE}" == "Digitized Film (DPX package)" ]] ; then
     if [[ -z "${DPXID}" ]] ; then
         printf "Enter your DPX_Object_ID_Number with underscores:"
         read -e DPXID
-        printf "ex. 2015_167_10_1\n%s"
+        printf "ex. 2015_167_10_1"
     fi
     if [[ -z "${DPXTITLE}" ]] ; then
         printf "Enter your DPX_Object_Title with underscores:"
-        printf "ex. Juke_Joint\n%s"
+        printf "ex. Juke_Joint"
         read -e DPXTITLE
     fi
     MEDIAID="${DPXID}__${DPXTITLE}"
@@ -269,18 +269,18 @@ if [[ "${PACKAGETYPE}" != "Digitized Film (DPX package)" ]] ; then
     RSYNC_ERR="${?}"
     if [[ -n "${RSYNC_ERR}" ]] && [[ "${RSYNC_ERR}" -gt "0" ]] ; then
         echo "${RSYNC_ERR}"
-        printf "${BIRED}rsync process failed. Exiting script...${COLOR_OFF}\n"
-        exit 1
+        _report -rt  "ERROR: rsync process failed. Exiting..."
         _log -a "Process terminated by script (rsync failure)."
+        exit 1
     fi
 fi
 # clean up original files if requested - hardcoded OFF during testing
 #if [[ "${CLEANUPDECISION}" == "Remove source files after successful ingest" ]] ; then
 #    if [[ -n "${RSYNC_ERR}" ]] && [[ "${RSYNC_ERR}" -gt "0" ]] ; then
 #        echo "${RSYNC_ERR}"
-#        printf "${BIRED}" "Cancelling requested deletion of source file, not looking safe." "${COLOR_OFF}"
+#        _report -rt  "Cancelling requested deletion of source file, not looking safe."
 #    else
-#        printf "${BIWHITE}" "Removing the source file from ${INPUT} as requested." "${COLOR_OFF}"
+#        _report -g "Removing the source file from ${INPUT} as requested..."
 #        _run rm -f "${INPUT}"
 #    fi
 #fi
@@ -289,4 +289,4 @@ fi
 _log -e
 _writelog "END TIME" "$(date +%FT%T)"
 
-printf "Process done...might have been successful...it's a WIP.\n"
+printf "Process done...might have been successful...it's a WIP."
diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -42,22 +42,22 @@ for DRIVE ; do # loop over all the drives provided by the operator
         if [[ -d "${FOLDER}" ]] ; then # if the output's parent folder structure is recognized as a directory:
             tree --filelimit 50 --si --du -U -Q -o "${OUTPUT}" "${DRIVE}" # create a tree of the drive's contents
             if grep "0 directories, 0 files" "${OUTPUT}" ; then # if the results of "tree," sent to the output text file, show that the drive was empty:
-                printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${BIWHITE}" "${DRIVE}" "${COLOR_OFF}" && OUTPUTE="${FOLDER}/${DRIVE##*/}_contents_${date}_EMPTY.txt" && mv -v "${OUTPUT}" "${OUTPUT}E"
-                printf "%sMoving %s to %s\n%s" "${BIWHITE}" "${OUTPUTE##*/}" "${DRIVE}" "${COLOR_OFF}" # tell operator the tree file is being moved to the drive
+                _report -g "${DRIVE} is empty. Adding EMPTY to file name." && OUTPUTE="${FOLDER}/${DRIVE##*/}_contents_${date}_EMPTY.txt" && mv -v "${OUTPUT}" "${OUTPUTE}"
+                _report -g "Moving ${OUTPUTE##*/} to ${DRIVE}" # tell operator the tree file is being moved to the drive
                 cp -v "${OUTPUTE}" "${DRIVE}" # copy the output text file to the drive: -v=verbose
             else
-                printf "%sMoving %s to %s\n%s" "${BIWHITE}" "${DRIVE}" "${COLOR_OFF}" # tell operator the tree file is being moved to the drive
+                _report -g "Moving ${OUTPUT##*/} to ${DRIVE}" # tell operator the tree file is being moved to the drive
                 cp -va "${OUTPUT}" "${DRIVE}" # copy the output text file to the drive: -v=verbose, -a="archive"
             fi
         else
-            printf "%sERROR: %s does not exist. Exiting.\n" "${BIRED}" "${FOLDER}" >&2 # tell operator if the hardcoded "local folder" cannot be found - e.g. no longer exists or is moved
+            _report -rt "ERROR: ${FOLDER} does not exist. Exiting..." >&2 # tell operator if the hardcoded "local folder" cannot be found - e.g. no longer exists or is moved
             _log -a "Process terminated by script (no directory at requested location)."
             exit
         fi
     else
-        printf "%sERROR: %s does not exist. Exiting.\n" "${BIRED}" "${DRIVE}" >&2 # tell operator if the drive cannot be found
+        _report -rt "ERROR: ${DRIVE} does not exist. Exiting..." >&2 # tell operator if the drive cannot be found
         _log -a "Process terminated by script (no drive at requested location)."
-        exit
+        exit 1
     fi
 done
 }
@@ -69,5 +69,5 @@ _log -b
 _makedrivetree "${@}"
 # log script ending
 _log -e
-printf "${BIWHITE}makedrivetree process complete.${COLOR_OFF}\n"
+_report -g "makedrivetree process complete."
 exit "$?"
diff --git a/restructureSIP b/restructureSIP
--- a/restructureSIP
+++ b/restructureSIP
@@ -58,7 +58,7 @@ shift $(( ${OPTIND} - 1 ))
 
 # check that all inputs were entered
 if [[ -z "${PACKAGETYPE}" ]] ; then
-    printf "Select a package type:"
+    _report -b "Select a package type:"
     echo
     PS3="Selection: "
     select PACKAGETYPE in "Digitized Film (DPX package)" "Digitized Film (MOV and/or MP4 files only)" "Digitized Analog Video (vrecord package)" "Transferred DV (MOV and/or MP4 files)" "Other/Unknown"
@@ -67,15 +67,15 @@ if [[ -z "${PACKAGETYPE}" ]] ; then
     done
 fi
 if [[ -z "${MEDIAID}" ]] && [[ "${PACKAGETYPE}" != "Digitized Film (DPX package)" ]] ; then
-    printf "Enter a unique package name or 'q' to quit: "
+    _report -b "Enter a unique package name or 'q' to quit: "
     read -e MEDIAID
     [[ "${MEDIAID}" = "q" ]] && exit 0
     # validate id and perhaps fail with exit
-    [[ -z "${MEDIAID}" ]] && { printf "${BIRED}ERROR You must enter a valid MEDIA ID${COLOR_OFF}\n" ; exit ;};
-    [[ ! -z $(echo "${MEDIAID}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { printf "ERROR The MEDIA ID must only contain letters, numbers, hyphen and underscore\n" ; exit 1 ;};
+    [[ -z "${MEDIAID}" ]] && { _report -rt "ERROR: You must enter a valid MEDIA ID" ; exit ;};
+    [[ ! -z $(echo "${MEDIAID}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { _report -rt "ERROR: The MEDIA ID must only contain letters, numbers, hyphen and underscore" ; exit 1 ;};
 fi
 if [[ -z "${DESTINATION}" ]] ; then
-    printf "Drag in the destination directory or type 'q' to quit: "
+    _report -b "Drag in the destination directory or type 'q' to quit: "
     read -e DESTINATION
     [[ "${DESTINATION}" = "q" ]] && exit 0
 fi
@@ -100,15 +100,18 @@ OUTPUT_PACKAGE="${DESTINATION}/${MEDIAID}"
 # if package type is unknown, check whether it looks like a DPX package
 if [[ "${PACKAGETYPE}" == "Other/Unknown" ]] ; then
     if [[ -n $(find "${INPUT}" -iname *.dpx) ]] ; then
-        printf "${bired}This SIP looks like a DPX package!${color_off}"
+        _report -g "This SIP looks like a DPX package!"
         PACKAGETYPE="Digitized Film (DPX package)"
     fi
 fi
 
 # if SIP is a DPX, direct the operator to use restructureDPX instead
 if [[ "${PACKAGETYPE}" == "Digitized Film (DPX package)" ]] ; then
-    printf "${bired}If you are trying to restructure a DPX package, please run the 'restructureDPX' microservice instead."
-    printf "You can also run the 'ingestfile' microservice, which invokes 'restructureDPX' as well.${color_off}"
+    _report -rt "If you are trying to restructure a DPX package, please run the 'restructureDPX' microservice instead!"
+    _report -b "You can also run the 'ingestfile' microservice, which invokes 'restructureDPX' as well."
+    cowsay "Thanks!"
+    _log -a "Process terminated by script (operator redirected to appropriate microservice)."
+    exit 0
 else
     mkdir "${OUTPUT_PACKAGE}" "${OUTPUT_PACKAGE}/objects" "${OUTPUT_PACKAGE}/metadata"
 fi
@@ -156,9 +159,9 @@ fi
 #if [[ "${CLEANUPDECISION}" == "Remove source files after successful ingest" ]] ; then
 #    if [[ -n "${RSYNC_ERR}" ]] && [[ "${RSYNC_ERR}" -gt "0" ]] ; then
 #        echo "${RSYNC_ERR}"
-#        printf "${BIRED}Cancelling requested deletion of source file, not looking safe.${COLOR_OFF}"
+#        _report -rt "Cancelling requested deletion of source file, not looking safe."
 #    else
-#        printf "${BIWHITE}Removing the source file from ${INPUT} as requested.${COLOR_OFF}"
+#        _report -g "Removing the source file from ${INPUT} as requested."
 #        _run rm -f "${INPUT}"
 #    fi
 #fi
