ingestfile lowercase update

diff --git a/ingestfile b/ingestfile
--- a/ingestfile
+++ b/ingestfile
@@ -139,7 +139,7 @@ if [[ -z "${PACKAGENAME}" ]] ; then
     [[ "${PACKAGENAME}" = "q" ]] && exit 0
     # validate id and perhaps fail with exit
     [[ -z "${PACKAGENAME}" ]] && { printf "${bired}ERROR You must enter a valid MEDIA ID${color_off}\n" ; exit ;};
-    [[ ! -z $(echo "${PACKAGENAME}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { printf "ERROR The MEDIA ID must only contain capital letters, numbers, hyphen and underscore" ; exit 1 ;};
+    [[ ! -z $(echo "${PACKAGENAME}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { printf "ERROR The MEDIA ID must only contain letters, numbers, hyphen and underscore\n" ; exit 1 ;};
 fi
 if [[ -z "${PACKAGETYPE}" ]] ; then
     _report -q "Select a package type:"
