variable -> VARIABLE
Change all variables to uppercase for standardization and quick identification.

diff --git a/ingestfile b/ingestfile
--- a/ingestfile
+++ b/ingestfile
@@ -3,9 +3,9 @@
 # a script to turn SIPs into AIPs
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -169,7 +169,7 @@ if [[ -z "${MEDIAID}" ]] && [[ "${PACKAGETYPE}" == "Digitized Film (DPX package)
     read -e MEDIAID
     [[ "${MEDIAID}" = "q" ]] && exit 0
     # validate id and perhaps fail with exit
-    [[ -z "${MEDIAID}" ]] && { printf "${bired}ERROR You must enter a valid MEDIA ID${color_off}\n" ; exit ;};
+    [[ -z "${MEDIAID}" ]] && { printf "${BIRED}ERROR You must enter a valid MEDIA ID${COLOR_OFF}\n" ; exit ;};
     [[ ! -z $(echo "${MEDIAID}" | grep -v "^[A-Za-z0-9_-]*$") ]] && { printf "ERROR The MEDIA ID must only contain letters, numbers, hyphen and underscore\n" ; exit 1 ;};
 fi
 if [[ -z "${PACKAGETYPE}" ]] ; then
@@ -240,28 +240,28 @@ mkdir -p "${DESTINATION}/${MEDIAID}"
 if [[ "${PACKAGETYPE}" == "Digitized Film (DPX package)" ]] ; then
     # if working with a DPX package, run restructureDPX microservice
     if [[ "${CLEANUPDECISION}" == "Leave source files where they are" ]] ; then
-        "${script_path}/restructureDPX" -d "${DESTINATION}" -i "${DPXID}" -t "${DPXTITLE}" -r "${REELS}" "${INPUT}"
+        "${SCRIPT_PATH}/restructureDPX" -d "${DESTINATION}" -i "${DPXID}" -t "${DPXTITLE}" -r "${REELS}" "${INPUT}"
     elif [[ "${CLEANUPDECISION}" == "Remove source files after successful ingest" ]] ; then
-        "${script_path}/restructureDPX" -d "${DESTINATION}" -i "${DPXID}" -t "${DPXTITLE}" -r "${REELS}" -c "${INPUT}"
+        "${SCRIPT_PATH}/restructureDPX" -d "${DESTINATION}" -i "${DPXID}" -t "${DPXTITLE}" -r "${REELS}" -c "${INPUT}"
     fi
 elif [[ "${PACKAGETYPE}" == "Digitized Film (MOV and/or MP4 files only)" ]] ; then
     # verify package structure matches expected (microservice tk)
-    "${script_path}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
-    "${script_path}/makeH264" "${INPUT}"
+    "${SCRIPT_PATH}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
+    "${SCRIPT_PATH}/makeH264" "${INPUT}"
     # restructure package (microservice tk)
 elif [[ "${PACKAGETYPE}" == "Digitized Analog Video (vrecord package)" ]] ; then
     # verify package structure matches expected (microservice tk)
-    "${script_path}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
-    "${script_path}/makeH264" "${INPUT}"
+    "${SCRIPT_PATH}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
+    "${SCRIPT_PATH}/makeH264" "${INPUT}"
     # restructure package (microservice tk)
 elif [[ "${PACKAGETYPE}" == "Transferred DV (MOV and/or MP4 files)" ]] ; then
     # verify package structure matches expected (microservice tk)
-    "${script_path}/makemetadata" -mq "${INPUT}" # make metadata files, including MD5 and QCTools files  if not present
-    "${script_path}/makeH264" "${INPUT}"
+    "${SCRIPT_PATH}/makemetadata" -mq "${INPUT}" # make metadata files, including MD5 and QCTools files  if not present
+    "${SCRIPT_PATH}/makeH264" "${INPUT}"
     # restructure package (microservice tk)
 elif [[ "${PACKAGETYPE}" == "Other/Unknown" ]] ; then
-    "${script_path}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
-    "${script_path}/makeH264" "${INPUT}"
+    "${SCRIPT_PATH}/makemetadata" -m "${INPUT}" # make metadata files, including MD5 file if not present
+    "${SCRIPT_PATH}/makeH264" "${INPUT}"
     # restructure package (microservice tk)
 fi
 
@@ -271,7 +271,7 @@ if [[ "${PACKAGETYPE}" != "Digitized Film (DPX package)" ]] ; then
     RSYNC_ERR="${?}"
     if [[ -n "${RSYNC_ERR}" ]] && [[ "${RSYNC_ERR}" -gt "0" ]] ; then
         echo "${RSYNC_ERR}"
-        printf "${bired}rsync process failed. Exiting script...${color_off}\n"
+        printf "${BIRED}rsync process failed. Exiting script...${COLOR_OFF}\n"
         exit 1
         _log -a "Process terminated by script (rsync failure)."
     fi
@@ -280,9 +280,9 @@ fi
 #if [[ "${CLEANUPDECISION}" == "Remove source files after successful ingest" ]] ; then
 #    if [[ -n "${RSYNC_ERR}" ]] && [[ "${RSYNC_ERR}" -gt "0" ]] ; then
 #        echo "${RSYNC_ERR}"
-#        printf "${bired}" "Cancelling requested deletion of source file, not looking safe." "${color_off}"
+#        printf "${BIRED}" "Cancelling requested deletion of source file, not looking safe." "${COLOR_OFF}"
 #    else
-#        printf "${biwhite}" "Removing the source file from ${INPUT} as requested." "${color_off}"
+#        printf "${BIWHITE}" "Removing the source file from ${INPUT} as requested." "${COLOR_OFF}"
 #        _run rm -f "${INPUT}"
 #    fi
 #fi
diff --git a/makeDer b/makeDer
--- a/makeDer
+++ b/makeDer
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -16,7 +16,7 @@ EXTENSION="mp4"
 # this function needs to be defined before the getopts loop as it is used within that loop
 _check_outputdir_forced(){
     if [[ ! -d "${OUTPUTDIR_FORCED}" ]] ; then
-        printf "\n${bired}The directory, ${OUTPUTDIR_FORCED}, does not exist. Can not write the output of $(basename "${0}").${color_off}\n"
+        printf "\n${BIRED}The directory, ${OUTPUTDIR_FORCED}, does not exist. Can not write the output of $(basename "${0}").${COLOR_OFF}\n"
         exit 1
     else
         echo "outputdirectory is ${OUTPUTDIR_FORCED}"
@@ -70,24 +70,24 @@ while [ "${*}" != "" ] ; do
     else
         OUTPUT_DIR="${OUTPUTDIR_FORCED}"
     fi
-    printf "Output directory is: ${biwhite}${OUTPUT_DIR}${color_off}\n"
+    printf "Output directory is: ${BIWHITE}${OUTPUT_DIR}${COLOR_OFF}\n"
     
     # set parent directory (the directory containing $OUTPUT_DIR) - currently not used
     PARENTDIR="$(dirname "${OUTPUT_DIR}")"
-    printf "Parent directory is: ${biwhite}${PARENTDIR}${color_off}\n"
+    printf "Parent directory is: ${BIWHITE}${PARENTDIR}${COLOR_OFF}\n"
 
     #set $MEDIAID to basename of $INPUT with extension stripped
     MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
-    printf "Media ID is: ${biwhite}$(basename "${INPUT}" | cut -d. -f1)${color_off}\n"
+    printf "Media ID is: ${BIWHITE}$(basename "${INPUT}" | cut -d. -f1)${COLOR_OFF}\n"
 
     #set $OUTPUT
     OUTPUT="${OUTPUT_DIR}/${MEDIAID%.*}${SUFFIX}.${EXTENSION}"
-    printf "Output is: ${biwhite}${OUTPUT}${color_off}\n"
+    printf "Output is: ${BIWHITE}${OUTPUT}${COLOR_OFF}\n"
 
     #check to see if $OUTPUT exists
     if [[ -s "${OUTPUT}" ]] ; then
-        printf "${bired}WARNING ${OUTPUT} already exists, skipping transcode\n"
-        printf "Moving to next file if present...\n${color_off}"
+        printf "${BIRED}WARNING ${OUTPUT} already exists, skipping transcode\n"
+        printf "Moving to next file if present...\n${COLOR_OFF}"
     else
         echo
 cat <<-EOF
@@ -101,7 +101,7 @@ cat <<-EOF
     If the output looks good, then try a higher value. If it looks bad then choose a lower value.
 EOF
         echo
-        printf "${biwhite}Please enter a CRF value: ${color_off}"
+        printf "${BIWHITE}Please enter a CRF value: ${COLOR_OFF}"
         read CRFVALUE
         echo
 cat <<-EOF
@@ -114,13 +114,13 @@ cat <<-EOF
     The general guideline is to use the slowest preset that you have patience for.
     Current presets in descending order of speed are:
 EOF
-    printf "${bired}ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow${color_off}"
+    printf "${BIRED}ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow${COLOR_OFF}"
         echo
-        printf "${biwhite}Please enter a preset speed: ${color_off}"
+        printf "${BIWHITE}Please enter a preset speed: ${COLOR_OFF}"
         read PRESETSPEED
 
         # have script say what is about to do
-        printf "\n${biwhite}Making .mp4 derivative of $(basename ${MEDIAID})${color_off}\n"
+        printf "\n${BIWHITE}Making .mp4 derivative of $(basename ${MEDIAID})${COLOR_OFF}\n"
         mkdir -p "${OUTPUT_DIR}"
         #mv -v "${INPUT}" "${PARENTDIR}"
 
@@ -136,10 +136,10 @@ EOF
         # rename file to indicate derivative
         # works by finding all mp4s in the output directory that have "PM" or "DER_01" in their filename; the "if" executes if any files matching those patterns are found (i.e. if the find statement executes to non-empty "-n")
         if [[ -n $(find "${OUTPUT_DIR}" -type f -name "*PM*.mp4" ) ]]; then
-            rename 's/PM/DER_02/' *.mp4 && printf "\n${biwhite}Updated derivative filename to reflect current name : PM to DER_02${color_off}\n"
+            rename 's/PM/DER_02/' *.mp4 && printf "\n${BIWHITE}Updated derivative filename to reflect current name : PM to DER_02${COLOR_OFF}\n"
         fi
         if [[ -n $(find "${OUTPUT_DIR}" -type f -name "*DER_01*.mp4" ) ]]; then
-            rename 's/DER_01/DER_03/' *.mp4 && printf "\n${biwhite}Updated derivative filename to reflect current name conventions: DER_01 to DER_03${color_off}\n"
+            rename 's/DER_01/DER_03/' *.mp4 && printf "\n${BIWHITE}Updated derivative filename to reflect current name conventions: DER_01 to DER_03${COLOR_OFF}\n"
         fi
     fi
     shift
@@ -147,4 +147,4 @@ done
 
 # log script ending
 _log -e
-printf "${biwhite}makeDer process complete.${color_off}\n"
+printf "${BIWHITE}makeDer process complete.${COLOR_OFF}\n"
diff --git a/makeH264 b/makeH264
--- a/makeH264
+++ b/makeH264
@@ -4,19 +4,19 @@
 # all comments refer to line(s) above unless placed in-line with code or specified otherwise
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
-relativepath="derivative"
-suffix="" #suffix is blank here but can be filled in with desired characters for inlcusion in filename
-extension="mp4"
-crfvalue=18
-presetspeed=medium
-maxrate=8000
-errors=0
+RELATIVEPATH="derivative"
+SUFFIX="" #SUFFIX is blank here but can be filled in with desired characters for inlcusion in filename
+EXTENSION="mp4"
+CRFVALUE=18
+PRESETSPEED=medium
+MAXRATE=8000
+ERRORS=0
 
 ## USAGE
 
@@ -47,61 +47,61 @@ shift $(( ${OPTIND} - 1 ))
 _log -b
 
 while [ "${*}" != "" ] ; do
-    input="${1}" #set $input as the first argument sent to script
+    INPUT="${1}" #set $INPUT as the first argument sent to script
 
-    # process if input is a file
-    if [[ -f "${input}" ]] ; then
-        output_dir="$(dirname ${input})/${relativepath}" # set output_dir to input name with extension stripped plus relativepath
-        MEDIAID="${input##*/}" #set $MEDIAID to basename of $input
+    # process if INPUT is a file
+    if [[ -f "${INPUT}" ]] ; then
+        OUTPUT_DIR="$(dirname ${INPUT})/${RELATIVEPATH}" # set OUTPUT_DIR to INPUT name with extension stripped plus relativepath
+        MEDIAID="${INPUT##*/}" #set $MEDIAID to basename of $INPUT
         MEDIAID="${MEDIAID%.*}" #set $MEDIAID to $MEDIAID with extension stripped
-        output="${output_dir}/${MEDIAID%.*}${suffix}.${extension}" #set $output
-        [[ ! -d "${output_dir}" ]] && mkdir -p "${output_dir}" # make output directory if it doesn't already exist
-        if [[ -s "${output}" ]] ; then #check to see if $output exists
-            printf "%sWARNING ${output} already exists, skipping transcode of %s.%s%s\n" "${bired}" "${input}" "${color_off}" "${biwhite}"
-            printf "Moving to next file if present...\n${color_off}"
+        OUTPUT="${OUTPUT_DIR}/${MEDIAID%.*}${SUFFIX}.${EXTENSION}" #set $OUTPUT
+        [[ ! -d "${OUTPUT_DIR}" ]] && mkdir -p "${OUTPUT_DIR}" # make OUTPUT directory if it doesn't already exist
+        if [[ -s "${OUTPUT}" ]] ; then #check to see if $OUTPUT exists
+            printf "%sWARNING ${OUTPUT} already exists, skipping transcode of %s.%s%s\n" "${BIRED}" "${INPUT}" "${COLOR_OFF}" "${BIWHITE}"
+            printf "Moving to next file if present...\n${COLOR_OFF}"
         else
-            printf "%sMEDIAID is: %s%s\n" "${color_off}" "${biwhite}" "${MEDIAID}"
-            printf "%sThe output directory is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir}"
-            printf "%soutput is: %s%s\n" "${color_off}" "${biwhite}" "${output}"
-            printf "\n%smaking .mp4 derivative of %s%s%s\n" "${color_off}" "${biwhite}" "${MEDIAID}" "${color_off}" 
-            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${input}" -movflags faststart -map 0:v -map 0:a -c:v libx264 -vf "yadif=1,format=yuv420p" -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
-            if [[ -s "${output}" ]] ; then
-                printf "\nSuccess! Derivative ${biwhite}$(basename ${output})${color_off} created.\n\n"
+            printf "%sMEDIAID is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${MEDIAID}"
+            printf "%sThe OUTPUT directory is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${OUTPUT_DIR}"
+            printf "%sOUTPUT is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${OUTPUT}"
+            printf "\n%smaking .mp4 derivative of %s%s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${MEDIAID}" "${COLOR_OFF}" 
+            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${INPUT}" -movflags faststart -map 0:v -map 0:a -c:v libx264 -vf "yadif=1,format=yuv420p" -crf "${CRFVALUE}" -preset "${PRESETSPEED}" -MAXRATE "${MAXRATE}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${OUTPUT}"
+            if [[ -s "${OUTPUT}" ]] ; then
+                printf "\nSuccess! Derivative ${BIWHITE}$(basename ${OUTPUT})${COLOR_OFF} created.\n\n"
             else
-                printf "\n${bired}Hmm...derivative $(basename ${output}) not successfully created.\n\n${color_off}"
-                ((errors++))
+                printf "\n${BIRED}Hmm...derivative $(basename ${OUTPUT}) not successfully created.\n\n${COLOR_OFF}"
+                ((ERRORS++))
             fi
-            printf "Moving to next file if present...\n${color_off}"
+            printf "Moving to next file if present...\n${COLOR_OFF}"
         fi
-    # process if input is a directory
-    elif [[ -d "${input}" ]] ; then
-        input="${input%/}" # strip trailing / if any
-        output_dir="${input}/${relativepath}" # set output_dir to input name plus relativepath
+    # process if INPUT is a directory
+    elif [[ -d "${INPUT}" ]] ; then
+        INPUT="${INPUT%/}" # strip trailing / if any
+        OUTPUT_DIR="${INPUT}/${RELATIVEPATH}" # set OUTPUT_DIR to INPUT name plus relativepath
         shopt -s nullglob # setting the nullglob option tells the for loop in the next line to skip the rest of the commands if it doesn't find any .mov and/or .mkv files (rather than try to execute on the literal string "*.mov" or "*.mkv")
-        for file in "${input}"/*.{mov,mkv} ; do # find .mov and .mkv files within the directory and run the ffmpeg command on that file
-            [[ ! -d "${output_dir}" ]] && mkdir -p "${output_dir}" # make output directory if it doesn't already exist
-            MEDIAID="${file##*/}" #set $MEDIAID to basename of $input
+        for FILE in "${INPUT}"/*.{mov,mkv} ; do # find .mov and .mkv files within the directory and run the ffmpeg command on that file
+            [[ ! -d "${OUTPUT_DIR}" ]] && mkdir -p "${OUTPUT_DIR}" # make OUTPUT directory if it doesn't already exist
+            MEDIAID="${FILE##*/}" #set $MEDIAID to basename of $INPUT
             MEDIAID="${MEDIAID%.*}" #set $MEDIAID to $MEDIAID with extension stripped
-            output="${output_dir}/${MEDIAID%.*}${suffix}.${extension}" #set $output
-            if [[ -s "${output}" ]] ; then #check to see if $output exists
-                printf "%sWARNING ${output} already exists, skipping transcode of %s.%s%s\n" "${bired}" "${input}" "${color_off}" "${biwhite}"
+            OUTPUT="${OUTPUT_DIR}/${MEDIAID%.*}${SUFFIX}.${EXTENSION}" #set $OUTPUT
+            if [[ -s "${OUTPUT}" ]] ; then #check to see if $OUTPUT exists
+                printf "%sWARNING ${OUTPUT} already exists, skipping transcode of %s.%s%s\n" "${BIRED}" "${INPUT}" "${COLOR_OFF}" "${BIWHITE}"
             else
-                printf "%sMEDIAID is: %s%s\n" "${color_off}" "${biwhite}" "${MEDIAID}"
-                printf "%sThe output directory is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir}"
-                printf "%soutput is: %s%s\n" "${color_off}" "${biwhite}" "${output}"
-                printf "\n%smaking .mp4 derivative of %s%s%s\n" "${color_off}" "${biwhite}" "${MEDIAID}" "${color_off}" 
-                ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${file}" -movflags faststart -pix_fmt yuv420p -map 0:v -map 0:a -c:v libx264 -vf "yadif=1,format=yuv420p" -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
-                if [[ -s "${output}" ]] ; then
-                    printf "\nSuccess! Derivative ${biwhite}$(basename ${output})${color_off} created.\n\n"
+                printf "%sMEDIAID is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${MEDIAID}"
+                printf "%sThe OUTPUT directory is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${OUTPUT_DIR}"
+                printf "%sOUTPUT is: %s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${OUTPUT}"
+                printf "\n%smaking .mp4 derivative of %s%s%s\n" "${COLOR_OFF}" "${BIWHITE}" "${MEDIAID}" "${COLOR_OFF}" 
+                ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${FILE}" -movflags faststart -pix_fmt yuv420p -map 0:v -map 0:a -c:v libx264 -vf "yadif=1,format=yuv420p" -crf "${CRFVALUE}" -preset "${PRESETSPEED}" -MAXRATE "${MAXRATE}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${OUTPUT}"
+                if [[ -s "${OUTPUT}" ]] ; then
+                    printf "\nSuccess! Derivative ${BIWHITE}$(basename ${OUTPUT})${COLOR_OFF} created.\n\n"
                 else
-                    printf "\n${bired}Hmm...derivative $(basename ${output}) not successfully created.\n\n${color_off}"
-                    ((errors++))
+                    printf "\n${BIRED}Hmm...derivative $(basename ${OUTPUT}) not successfully created.\n\n${COLOR_OFF}"
+                    ((ERRORS++))
                 fi
             fi
-            printf "Moving to next file if present...\n${color_off}"
+            printf "Moving to next file if present...\n${COLOR_OFF}"
         done
     else
-        printf "${bired}Input is not a file or directory. Exiting script..."
+        printf "${BIRED}Input is not a file or directory. Exiting script..."
         exit 1
     fi
     shift
@@ -109,10 +109,10 @@ done
 
 # log script ending
 _log -e
-printf "${biwhite}makeH264 process complete.\n${color_off}"
-if [[ "${errors}" -gt 0 ]] ; then
-    printf "\n${bired}Not all derivatives were successfully created. Please double-check the terminal output!\n"
-    printf "Number of derivative errors found: ${errors}\n${color_off}"
-    _log -w "${errors} error/s occurred during derivative creation."
+printf "${BIWHITE}makeH264 process complete.\n${COLOR_OFF}"
+if [[ "${ERRORS}" -gt 0 ]] ; then
+    printf "\n${BIRED}Not all derivatives were successfully created. Please double-check the terminal OUTPUT!\n"
+    printf "Number of derivative errors found: ${ERRORS}\n${COLOR_OFF}"
+    _log -w "${ERRORS} error/s occurred during derivative creation."
 fi
 exit "$?"
diff --git a/makechecksum b/makechecksum
--- a/makechecksum
+++ b/makechecksum
@@ -3,9 +3,9 @@
 #a script to create md5 checksums of all files in a directory or a single file and save it to a .md5 file
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -36,39 +36,39 @@ makechecksum(){
     echo
     while [[ $# -gt 0 ]] ; do
         1
-        input="${1}" #name $input as the first argument sent to script
+        INPUT="${1}" #name $INPUT as the first argument sent to script
 
-        if [ -d "${input}" ] ; then #if argument is a directory, run md5deep
-            target="${input%/}" #strip the trailing /, if any
-            target="${target##*/}" #drop the leading directory components i.e. get basename
-            output="${input}/${target}_${date}_checksums.md5" #set .md5 file as $output
-            printf "%s%s%s is a directory.\n" "${biwhite}" "${target}" "${color_off}"
-            printf "Making checksums of all files in %s%s%s\n" "${biwhite}" "${target}" "${color_off}"
-            printf "Writing to %s%s%s\n" "${biwhite}" "${output}" "${color_off}"
-            md5deep -bre "${input}" >> "${output}" #create md5 hash (hashes) of $input and write results to $output. -b=strip leading directory info, -r=recursive, -e=display progress indicator
+        if [ -d "${INPUT}" ] ; then #if argument is a directory, run md5deep
+            TARGET="${INPUT%/}" #strip the trailing /, if any
+            TARGET="${TARGET##*/}" #drop the leading directory components i.e. get basename
+            OUTPUT="${INPUT}/${TARGET}_${date}_checksums.md5" #set .md5 file as $OUTPUT
+            printf "%s%s%s is a directory.\n" "${BIWHITE}" "${TARGET}" "${COLOR_OFF}"
+            printf "Making checksums of all files in %s%s%s\n" "${BIWHITE}" "${TARGET}" "${COLOR_OFF}"
+            printf "Writing to %s%s%s\n" "${BIWHITE}" "${OUTPUT}" "${COLOR_OFF}"
+            md5deep -bre "${INPUT}" >> "${OUTPUT}" #create md5 hash (hashes) of $INPUT and write results to $OUTPUT. -b=strip leading directory info, -r=recursive, -e=display progress indicator
         fi
 
-        if [ -f "${input}" ] ; then #if argument is a file, run md5deep
-            target="${input##*/}" #get basename of $input
-            target="${target%.*}" #strip extension from $target
-            output="${input%/*}" #get full path parent dirname of $input
-            output="${output}/${target}_${date}_checksums.md5" #set .md5 file as $output
-            printf "%s%s%s is a file.\n" "${biwhite}" "${input##*/}" "${color_off}"
-            printf "Making checksum of %s%s%s\n" "${biwhite}" "${input##*/}" "${color_off}"
-            printf "Writing to %s%s%s\n" "${biwhite}" "${output}" "${color_off}"
-            md5deep -bre "${input}" >> "${output}" #create md5 hash (hashes) of $input and write results to $output. -b=strip leading directory info, -r=recursive, -e=display progress indicator
+        if [ -f "${INPUT}" ] ; then #if argument is a file, run md5deep
+            TARGET="${INPUT##*/}" #get basename of $INPUT
+            TARGET="${TARGET%.*}" #strip extension from $TARGET
+            OUTPUT="${INPUT%/*}" #get full path parent dirname of $INPUT
+            OUTPUT="${OUTPUT}/${TARGET}_$(date +%F)_checksums.md5" #set .md5 file as $OUTPUT
+            printf "%s%s%s is a file.\n" "${BIWHITE}" "${INPUT##*/}" "${COLOR_OFF}"
+            printf "Making checksum of %s%s%s\n" "${BIWHITE}" "${INPUT##*/}" "${COLOR_OFF}"
+            printf "Writing to %s%s%s\n" "${BIWHITE}" "${OUTPUT}" "${COLOR_OFF}"
+            md5deep -bre "${INPUT}" >> "${OUTPUT}" #create md5 hash (hashes) of $INPUT and write results to $OUTPUT. -b=strip leading directory info, -r=recursive, -e=display progress indicator
         fi
 
         echo
-        printf "Sorting %s%s%s\n" "${biwhite}" "${output##*/}" "${color_off}"
-        sort -k 2 -o "${output}" "${output}" #sort $output. -k 2=sort on the second field, -o=write output to file (instead of standard terminal output)
+        printf "Sorting %s%s%s\n" "${BIWHITE}" "${OUTPUT##*/}" "${COLOR_OFF}"
+        sort -k 2 -o "${OUTPUT}" "${OUTPUT}" #sort $OUTPUT. -k 2=sort on the second field, -o=write OUTPUT to file (instead of standard terminal OUTPUT)
         shift
         echo
             if [[ $# -gt 0 ]] ; then
-                printf "Finished making checksums for %s%s%s.\n\n<>..<> Moving to %s%s%s\n" "${biwhite}" "${input##*/}" "${color_off}" "${biwhite}" "${1##*/}" "${color_off}"
+                printf "Finished making checksums for %s%s%s.\n\n<>..<> Moving to %s%s%s\n" "${BIWHITE}" "${INPUT##*/}" "${COLOR_OFF}" "${BIWHITE}" "${1##*/}" "${COLOR_OFF}"
                 echo
             else
-                printf "Finished making checksums for %s%s%s.\nNothing left to checksum.\n" "${biwhite}" "${input##*/}" "${color_off}"
+                printf "Finished making checksums for %s%s%s.\nNothing left to checksum.\n" "${BIWHITE}" "${INPUT##*/}" "${COLOR_OFF}"
                 echo
                 cowsay "Tootles!"
             fi
@@ -83,5 +83,5 @@ _log -b
 makechecksum "${@}"
 # log script ending
 _log -e
-printf "${biwhite}makechecksum process complete.${color_off}\n"
+printf "${BIWHITE}makechecksum process complete.${COLOR_OFF}\n"
 exit $?
diff --git a/makeconcat b/makeconcat
--- a/makeconcat
+++ b/makeconcat
@@ -3,9 +3,9 @@
 # a script to concat video files into a single file
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -34,26 +34,26 @@ shift $(( ${OPTIND} - 1 ))
 
 makeconcat(){
     echo
-    printf "%sPlease enter the name of the concatenated file to be created.\n\t For example, SC_0001_20171211_Mangum_R8_01\nEnter file name:%s " "${biwhite}" "${color_off}"
-    read -r concatfile
-    ## $concatfile will be the name of both the $txtfile and the outputed concatenated file. Name well.
+    printf "%sPlease enter the name of the concatenated file to be created.\n\t For example, SC_0001_20171211_Mangum_R8_01\nEnter file name:%s " "${BIWHITE}" "${COLOR_OFF}"
+    read -r CONCATFILE
+    ## $CONCATFILE will be the name of both the $TXTFILE and the outputed concatenated file. Name well.
     echo
     while [ "${*}" != "" ] ; do # while the number of arguments is not zero do X
-        for file in ${1} ; do # for the first argument do X
-            suffix="${file##*.}" # set $suffix to whatever the extension of your $file is
-            path="${file%/*}" # the $path is set as the dirname of the first argument
-            txtfile="${path}/${concatfile}.txt" # the $txtfile will be created in the same dir as the first argument and named after $concatfile
-            touch "${txtfile}" # the $txtfile is created, aka "touched"
-            printf "file '${file}'\n" >> "${txtfile}" # the first argument is written to $txtfile in the appropriate syntax for ffmpeg
+        for FILE in ${1} ; do # for the first argument do X
+            suffix="${FILE##*.}" # set $suffix to whatever the extension of your $FILE is
+            PATH="${FILE%/*}" # the $PATH is set as the dirname of the first argument
+            TXTFILE="${PATH}/${CONCATFILE}.txt" # the $TXTFILE will be created in the same dir as the first argument and named after $CONCATFILE
+            touch "${TXTFILE}" # the $TXTFILE is created, aka "touched"
+            printf "FILE '${FILE}'\n" >> "${TXTFILE}" # the first argument is written to $TXTFILE in the appropriate syntax for ffmpeg
             shift # the script shifts from the first argument to the second argument. It will do this until there are no more arguments.
         done
     done
-    concatfile="${path}/${concatfile}.$suffix"
-    ffmpeg -f concat -safe 0 -i "${txtfile}" -c copy "${concatfile}" # ffmpeg creates the concatenated file in the same directory as $files
+    CONCATFILE="${PATH}/${CONCATFILE}.$suffix"
+    ffmpeg -f concat -safe 0 -i "${TXTFILE}" -c copy "${CONCATFILE}" # ffmpeg creates the concatenated FILE in the same directory as $FILEs
     echo
-    cowsay "Done. Your concatenated video file is ready fo action." # cowsay tells it like it is.
+    cowsay "Done. Your concatenated video FILE is ready fo action." # cowsay tells it like it is.
     echo
-    printf "Your concatenated file is: %s" "${concatfile}\n"
+    printf "Your concatenated file is: %s" "${CONCATFILE}\n"
 }
 
 ## SCRIPT ACTIONS
@@ -63,5 +63,5 @@ _log -b
 makeconcat "${@}"
 # log script ending
 _log -e
-printf "${biwhite}makeconcat process complete.${color_off}\n"
+printf "${BIWHITE}makeconcat process complete.${COLOR_OFF}\n"
 exit "$?"
diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -3,9 +3,9 @@
 # a script to write the contents of a directory in tree form and save it to a .txt file
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -33,29 +33,29 @@ shift $(( ${OPTIND} - 1 ))
 ### FUNCTIONS
 
 makedrivetree(){
-local drive ; # set up local variable $drive
-local folder="/Volumes/UtilitySAN/05_driveContents"
-for drive ; do # loop over all the drives provided by the operator
-    drive="${drive%/}" # strip trailing / if any
-    if [[ -d "${drive}" ]] ; then # if the drive structure is recognized as a directory:
-        output="${folder}/${drive##*/}_contents_${date}.txt"
-        if [[ -d "${folder}" ]] ; then # if the output's parent folder structure is recognized as a directory:
-            tree --filelimit 50 --si --du -U -Q -o "${output}" "${drive}" # create a tree of the drive's contents
-            if grep "0 directories, 0 files" "${output}" ; then # if the results of "tree," sent to the output text file, show that the drive was empty:
-                printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${biwhite}" "${drive}" "${color_off}" && outputE="${folder}/${drive##*/}_contents_${date}_EMPTY.txt" && mv -v "${output}" "${output}E"
-                printf "%sMoving %s to %s\n%s" "${biwhite}" "${outputE##*/}" "${drive}" "${color_off}" # tell operator the tree file is being moved to the drive
-                cp -v "${outputE}" "${drive}" # copy the output text file to the drive: -v=verbose
+local DRIVE ; # set up local variable $DRIVE
+local FOLDER="/Volumes/UtilitySAN/05_driveContents"
+for DRIVE ; do # loop over all the drives provided by the operator
+    DRIVE="${DRIVE%/}" # strip trailing / if any
+    if [[ -d "${DRIVE}" ]] ; then # if the drive structure is recognized as a directory:
+        OUTPUT="${FOLDER}/${DRIVE##*/}_contents_${date}.txt"
+        if [[ -d "${FOLDER}" ]] ; then # if the output's parent folder structure is recognized as a directory:
+            tree --filelimit 50 --si --du -U -Q -o "${OUTPUT}" "${DRIVE}" # create a tree of the drive's contents
+            if grep "0 directories, 0 files" "${OUTPUT}" ; then # if the results of "tree," sent to the output text file, show that the drive was empty:
+                printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${BIWHITE}" "${DRIVE}" "${COLOR_OFF}" && OUTPUTE="${FOLDER}/${DRIVE##*/}_contents_${date}_EMPTY.txt" && mv -v "${OUTPUT}" "${OUTPUT}E"
+                printf "%sMoving %s to %s\n%s" "${BIWHITE}" "${OUTPUTE##*/}" "${DRIVE}" "${COLOR_OFF}" # tell operator the tree file is being moved to the drive
+                cp -v "${OUTPUTE}" "${DRIVE}" # copy the output text file to the drive: -v=verbose
             else
-                printf "%sMoving %s to %s\n%s" "${biwhite}" "${drive}" "${color_off}" # tell operator the tree file is being moved to the drive
-                cp -va "${output}" "${drive}" # copy the output text file to the drive: -v=verbose, -a="archive"
+                printf "%sMoving %s to %s\n%s" "${BIWHITE}" "${DRIVE}" "${COLOR_OFF}" # tell operator the tree file is being moved to the drive
+                cp -va "${OUTPUT}" "${DRIVE}" # copy the output text file to the drive: -v=verbose, -a="archive"
             fi
         else
-            printf "%sERROR: %s does not exist. Exiting.\n" "${bired}" "${folder}" >&2 # tell operator if the hardcoded "local folder" cannot be found - e.g. no longer exists or is moved
+            printf "%sERROR: %s does not exist. Exiting.\n" "${BIRED}" "${FOLDER}" >&2 # tell operator if the hardcoded "local folder" cannot be found - e.g. no longer exists or is moved
             _log -a "Process terminated by script (no directory at requested location)."
             exit
         fi
     else
-        printf "%sERROR: %s does not exist. Exiting.\n" "${bired}" "${drive}" >&2 # tell operator if the drive cannot be found
+        printf "%sERROR: %s does not exist. Exiting.\n" "${BIRED}" "${DRIVE}" >&2 # tell operator if the drive cannot be found
         _log -a "Process terminated by script (no drive at requested location)."
         exit
     fi
@@ -69,5 +69,5 @@ _log -b
 makedrivetree "${@}"
 # log script ending
 _log -e
-printf "${biwhite}makedrivetree process complete.${color_off}\n"
+printf "${BIWHITE}makedrivetree process complete.${COLOR_OFF}\n"
 exit "$?"
diff --git a/makemetadata b/makemetadata
--- a/makemetadata
+++ b/makemetadata
@@ -2,9 +2,9 @@
 # a script to generate metadata sidecar files for video files
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
@@ -110,11 +110,11 @@ while [ "${*}" != "" ] ; do
                 fi
             fi
         fi
-        printf "Moving to next file if present...\n${color_off}"
+        printf "Moving to next file if present...\n${COLOR_OFF}"
     done
     shift
 done
 
 # log script ending
 _log -e
-printf "${biwhite}makemetadata process complete.\n${color_off}"
+printf "${BIWHITE}makemetadata process complete.\n${COLOR_OFF}"
diff --git a/moveDPX b/moveDPX
--- a/moveDPX
+++ b/moveDPX
@@ -9,7 +9,7 @@ _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
 # (hardcoded) designated parent folder where the files will be moved
-target_folder_parent="/Users/Annie/Dropbox/Annie/2019_fall/NMAAHC-test-files/dpx_dest"
+TARGET_FOLDER_PARENT="/Users/Annie/Dropbox/Annie/2019_fall/NMAAHC-test-files/dpx_dest"
 
 ## USAGE
 
@@ -17,7 +17,7 @@ usage(){
     echo
     echo "$(basename "${0}")"
     echo "This application will copy .md5 checksum files and the first .dpx file in a stack to a designated directory. It takes one or more DPX directories as arguments."
-    echo "The files will be sent to a subdirectory of ${target_folder_parent}"
+    echo "The files will be sent to a subdirectory of ${TARGET_FOLDER_PARENT}"
     echo "Usage: $(basename ${0}) dpxdirectory1 [ dpxdirectory2 ...]"
     echo
     exit
@@ -38,63 +38,63 @@ shift $(( ${OPTIND} - 1 ))
 moveDPX(){
     while [[ "${*}" != "" ]] ; do
 
-        dpx_folder="${1}"
-        target_folder="${target_folder_parent}/${dpx_folder##*/}"
+        DPX_FOLDER="${1}"
+        TARGET_FOLDER="${TARGET_FOLDER_PARENT}/${DPX_FOLDER##*/}"
 
-        if [[ ! -d "${target_folder_parent}" ]] ; then 
+        if [[ ! -d "${TARGET_FOLDER_PARENT}" ]] ; then 
             echo
-            printf "${bired} %s%s does not exist. Exiting. ${color_off}\n" "${target_folder_parent}" >&2 # tell operator if the hardcoded parent folder cannot be found - e.g. no longer exists or is moved
+            printf "${BIRED} %s%s does not exist. Exiting. ${COLOR_OFF}\n" "${TARGET_FOLDER_PARENT}" >&2 # tell operator if the hardcoded parent folder cannot be found - e.g. no longer exists or is moved
             exit
         fi
 
-        if [[ ! -d "${target_folder}" ]] ; then
+        if [[ ! -d "${TARGET_FOLDER}" ]] ; then
             echo
-            printf "Creating target folder:\t%s%s%s\n" "${biwhite}" "${target_folder}" "${color_off}"
-            mkdir -p "${target_folder}"
+            printf "Creating target folder:\t%s%s%s\n" "${BIWHITE}" "${TARGET_FOLDER}" "${COLOR_OFF}"
+            mkdir -p "${TARGET_FOLDER}"
         fi
 
-        printf "${biwhite}Moving files to target folder...${color_off}\n"
+        printf "${BIWHITE}Moving files to target folder...${COLOR_OFF}\n"
         
-        for file in "${dpx_folder}"/*DPX*/* ; do # for all files in a DPX subdirectory (expected to be named with the word "DPX" in it), do the following:
-            if [[ -f "${target_folder}"/*.dpx ]] ; then # if .dpx file is found as expected, do:
+        for FILE in "${DPX_FOLDER}"/*DPX*/* ; do # for all files in a DPX subdirectory (expected to be named with the word "DPX" in it), do the following:
+            if [[ -f "${TARGET_FOLDER}"/*.dpx ]] ; then # if .dpx file is found as expected, do:
                 echo
-                printf "%s%s%s exists, verifying checksum.\n" "${biwhite}" "${file##*/}" "${color_off}"
-                rsync -avPhic "${file}" "${target_folder}" # move file securely to the target folder. -a="archive," -v=verbose, -P=keep partially transferred files+show progress during transfer, -h=human-readable, -i=itemize changes, -c=with a built-in checksum check
-                rsync_err_1="$?" # assign rsync output code to a variable
+                printf "%s%s%s exists, verifying checksum.\n" "${BIWHITE}" "${FILE##*/}" "${COLOR_OFF}"
+                rsync -avPhic "${FILE}" "${TARGET_FOLDER}" # move file securely to the target folder. -a="archive," -v=verbose, -P=keep partially transferred files+show progress during transfer, -h=human-readable, -i=itemize changes, -c=with a built-in checksum check
+                RSYNC_ERR_1="$?" # assign rsync output code to a variable
             else
-                rsync -avPhi "${file}" "${target_folder}" # move file securely to the target folder (no checksum check)
-                rsync_err_1="$?" # assign rsync output code to a variable
+                rsync -avPhi "${FILE}" "${TARGET_FOLDER}" # move file securely to the target folder (no checksum check)
+                RSYNC_ERR_1="$?" # assign rsync output code to a variable
             fi
-            printf "%srsync exit status is: %s%s\n" "${biwhite}" "${rsync_err_1}" "${color_off}"
+            printf "%srsync exit status is: %s%s\n" "${BIWHITE}" "${RSYNC_ERR_1}" "${COLOR_OFF}"
 
-            if [[ "${rsync_err_1}" == 0 ]] ; then # if rsync output code indicated the rsync transfer was successful, tell operator
+            if [[ "${RSYNC_ERR_1}" == 0 ]] ; then # if rsync output code indicated the rsync transfer was successful, tell operator
                 echo
-                printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${biwhite}" "${file##*/}" "${color_off}" "${biwhite}" "${target_folder}" "${color_off}"
+                printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${BIWHITE}" "${FILE##*/}" "${COLOR_OFF}" "${BIWHITE}" "${TARGET_FOLDER}" "${COLOR_OFF}"
                 echo
             else
-                printf "%sERRORS%s\n" "${bired}" "${color_off}" >&2
+                printf "%sERRORS%s\n" "${BIRED}" "${COLOR_OFF}" >&2
             fi
             break 1
         done
 
-        for md5 in "${dpx_folder}"/*.md5 ; do
-            if [[ -f "${target_folder}"/*.md5 ]] ; then # if .md5 checksum file is found as expected, do:
+        for MD5 in "${DPX_FOLDER}"/*.md5 ; do
+            if [[ -f "${TARGET_FOLDER}"/*.md5 ]] ; then # if .md5 checksum file is found as expected, do:
                 echo
-                printf "%s%s%s exists, verifying checksum.\n" "${biwhite}" "${md5##*/}" "${color_off}" # move file securely to the target folder (with built-in checksum check)
-                rsync -avPhic "${md5}" "${target_folder}"
-                rsync_err_2="$?" # assign rsync output code to a variable
+                printf "%s%s%s exists, verifying checksum.\n" "${BIWHITE}" "${md5##*/}" "${COLOR_OFF}" # move file securely to the target folder (with built-in checksum check)
+                rsync -avPhic "${MD5}" "${TARGET_FOLDER}"
+                RSYNC_ERR_2="$?" # assign rsync output code to a variable
             else
-                rsync -avPhi "${md5}" "${target_folder}"  # move file securely to the target folder (no checksum check)
-                rsync_err_2="$?" # assign rsync output code to a variable
+                rsync -avPhi "${MD5}" "${TARGET_FOLDER}"  # move file securely to the target folder (no checksum check)
+                RSYNC_ERR_2="$?" # assign rsync output code to a variable
             fi
-                printf "%srsync exit status is: %s%s\n" "${biwhite}" "${rsync_err_2}" "${color_off}"
+                printf "%srsync exit status is: %s%s\n" "${BIWHITE}" "${RSYNC_ERR_2}" "${COLOR_OFF}"
 
-            if [[ "${rsync_err_2}" == 0 ]] ; then # if rsync output code indicated the rsync transfer was successful, tell operator
+            if [[ "${RSYNC_ERR_2}" == 0 ]] ; then # if rsync output code indicated the rsync transfer was successful, tell operator
                 echo
-                printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${biwhite}" "${md5##*/}" "${color_off}" "${biwhite}" "${target_folder}" "${color_off}"
+                printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "${BIWHITE}" "${md5##*/}" "${COLOR_OFF}" "${BIWHITE}" "${TARGET_FOLDER}" "${COLOR_OFF}"
                 echo
             else
-                printf "${bired}rsync transfer not completed successfully!${color_off}\n" >&2
+                printf "${BIRED}rsync transfer not completed successfully!${COLOR_OFF}\n" >&2
             fi
         done
         printf "Moving to next DPX directory if supplied...\n"
@@ -102,8 +102,8 @@ moveDPX(){
         shift
 
     done
-    printf "%sChanged permissions on the following files in directory %s to 777:%s\n" "${biwhite}" "${target_folder_parent##*/}" "${color_off}"
-    chmod -vR 777 "${target_folder_parent}" # set permissions on the target parent directory (set above) to read-write-execute for all users. -v=verbose, -R=recursive
+    printf "%sChanged permissions on the following files in directory %s to 777:%s\n" "${BIWHITE}" "${TARGET_FOLDER_PARENT##*/}" "${COLOR_OFF}"
+    chmod -vR 777 "${TARGET_FOLDER_PARENT}" # set permissions on the target parent directory (set above) to read-write-execute for all users. -v=verbose, -R=recursive
 }
 
 ## SCRIPT ACTIONS
@@ -113,5 +113,5 @@ _log -b
 moveDPX "${@}"
 # log script ending
 _log -e
-printf "${biwhite}moveDPX process complete.${color_off}\n"
+printf "${BIWHITE}moveDPX process complete.${COLOR_OFF}\n"
 exit "$?"
diff --git a/nmaahcmmfunctions b/nmaahcmmfunctions
--- a/nmaahcmmfunctions
+++ b/nmaahcmmfunctions
@@ -10,9 +10,9 @@ WHAT_IS_THIS="NMAAHC mediamicroservices"
 # . /path/to/functions.sh
 # The script will interpret functions.sh as if its content were actually present in your file at this point. It is a common mechanism for implementing shared libraries of shell functions, and is how each script in nmaahcmm can reference the shared functions in this file.
 # Here is an example specific to NMAAHC:
-## script_path=${0%/*}      # script_path will be the directory path of {0} which is the script being called
-## . "${script_path}/nmaahcmmfunctions"         # loads the functions in nmaahcmmfunctions into this script
-## [[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};        # checks to see that that nmaahcmmfunctions exists; if it doesn't (left side of || exits non-zero) then it will execute the right side of ||
+## SCRIPT_PATH=${0%/*}      # SCRIPT_PATH will be the directory path of {0} which is the script being called
+## . "${SCRIPT_PATH}/nmaahcmmfunctions"         # loads the functions in nmaahcmmfunctions into this script
+## [[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};        # checks to see that that nmaahcmmfunctions exists; if it doesn't (left side of || exits non-zero) then it will execute the right side of ||
 
 # load configuration file
 if [ -f "${GM_CONFIG_FILE}" ] ; then
@@ -25,17 +25,17 @@ fi
 # set text colors; can be used to differentiate statements that display in the terminal window
 function _setcolors(){
     date="$(date +%Y%m%d)"
-    biwhite=$(tput bold)$(tput setaf 7)
-    bired=$(tput bold)$(tput setaf 1)
-    biyellow=$(tput bold)$(tput setaf 3)
-    gray=$(tput setaf 7)
-    color_off=$(tput sgr0)
+    BIWHITE=$(tput bold)$(tput setaf 7)
+    BIRED=$(tput bold)$(tput setaf 1)
+    BIYELLOW=$(tput bold)$(tput setaf 3)
+    GRAY=$(tput setaf 7)
+    COLOR_OFF=$(tput sgr0)
 }
 
 # this function helps the system gracefully exit the script; it will only run when the operator presses ctrl+C
 function _initialize_make(){
     _cleanup(){
-            printf "\n${bired}Process cancelled\n${color_off}" # tell operator that script is ending, then turn all colors off
+            printf "\n${BIRED}Process cancelled\n${COLOR_OFF}" # tell operator that script is ending, then turn all colors off
         exit 1
     }
     trap _cleanup SIGHUP SIGINT SIGTERM # "termination signals" that ask the system to clean up and safely kill the ongoing process, with increasing urgency
@@ -49,7 +49,7 @@ function _mkdir(){
         if [ ! -d "${DIR2MAKE}" ] ; then
             mkdir -p "${DIR2MAKE}"
             if [ "${?}" -ne 0 ]; then
-                printf "${bired}" "${0}: Can't create directory at ${DIR2MAKE}"
+                printf "${BIRED}" "${0}: Can't create directory at ${DIR2MAKE}"
                 exit 1
             fi
         fi
@@ -122,7 +122,7 @@ function _pashua_run(){
 
 function _check_deliverdir(){
     if [[ ! -d "${DELIVERDIR}" ]] ; then
-        printf "${bired}" "The delivery directory, ${DELIVERDIR}, does not exist. Can not deliver the OUTPUT of $(basename "${0}")." "${color_off}"
+        printf "${BIRED}" "The delivery directory, ${DELIVERDIR}, does not exist. Can not deliver the OUTPUT of $(basename "${0}")." "${COLOR_OFF}"
     fi
 }
 
diff --git a/restructureForVFCU b/restructureForVFCU
--- a/restructureForVFCU
+++ b/restructureForVFCU
@@ -3,29 +3,29 @@
 #a script to restructure a DPX package directory for VFCU pickup and place .md5 in driectory
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
 ### USAGE
 
-usage(){
+_usage(){
     echo
     echo "$(basename "${0}")"
     echo "This application will restructure a DPX package directory for VFCU pickup and place .md5s in a directory. It takes one or more DPX directories as arguments."
-    echo "Usage: $(basename ${0}) dpxdirectory1 [[ dpxdirectory2 ... ]"
+    echo "Usage: $(basename ${0}) DPXdirectory1 [[ DPXdirectory2 ... ]"
     echo
     exit
 }
-[[ "${#}" = 0 ]] && usage # if the command is run with no arguments then usage is called
+[[ "${#}" = 0 ]] && _usage # if the command is run with no arguments then _usage is called
 # getopts loop
 OPTIND=1
 while getopts ":h" OPT; do
     case "${OPT}" in
-        h) usage ;; # if the operator runs "[scriptname] -h" then the usage text above will display in the terminal
-        *) echo "Invalid option -${OPTARG}" ; usage ;; # if the operator tries to use an option other than the ones listed above, the usage text will display in the terminal
+        h) _usage ;; # if the operator runs "[scriptname] -h" then the _usage text above will display in the terminal
+        *) echo "Invalid option -${OPTARG}" ; _usage ;; # if the operator tries to use an option other than the ones listed above, the _usage text will display in the terminal
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -35,49 +35,49 @@ shift $(( ${OPTIND} - 1 ))
 restructureForVFCU(){
     echo
 
-    for arg in "${@}" ;
+    for ARG in "${@}" ;
     do
-        input="${1}" # name $input as the first argument sent to script
+        INPUT="${1}" # name $INPUT as the first argument sent to script
         # create subdirectories for each component
-        audio="${input}/${input##*/}"__Audio
-        derivatives="${input}/${input##*/}"__Derivatives
-        dpx="${input}/${input##*/}"__DPX
-        md5="/Volumes/nmaahc-borndigital/06_DPX_checksums/"
+        AUDIO_DIR="${INPUT}/${INPUT##*/}"__Audio
+        DERIV_DIR="${INPUT}/${INPUT##*/}"__Derivatives
+        DPX_DIR="${INPUT}/${INPUT##*/}"__DPX
+        MD5_DIR="/Volumes/nmaahc-borndigital/06_DPX_checksums/"
 
-        if [[ -d "${input}" ]] ; then
-            printf "%s%s%s is a directory.\n" "${biyellow}" "${input}" "${color_off}"
-            printf "Moving all files in:\n\t%s%s\n\t%s%s\n\tto:\n\t%s%s%s\n" "${biyellow}" "${audio}" "${derivatives}" "${color_off}" "${biyellow}" "${dpx}" "${color_off}"
+        if [[ -d "${INPUT}" ]] ; then
+            printf "%s%s%s is a directory.\n" "${BIYELLOW}" "${INPUT}" "${COLOR_OFF}"
+            printf "Moving all files in:\n\t%s%s\n\t%s%s\n\tto:\n\t%s%s%s\n" "${BIYELLOW}" "${AUDIO_DIR}" "${DERIV_DIR}" "${COLOR_OFF}" "${BIYELLOW}" "${DPX_DIR}" "${COLOR_OFF}"
             echo
-            printf "%s" "${gray}"
-            if [[ -d "${audio}" ]] ; then
-                mv -vi "${audio}"/* "${dpx}" # move all files in the audio directory to the DPX directory. -v=verbose, -i=interactive (prompts before overwriting)
-                rm -vri "${audio}" # removes the audio directory and any files left in it. -v=verbose, -r=recursive, -i=interactive (prompts before overwriting)
+            printf "%s" "${GRAY}"
+            if [[ -d "${AUDIO_DIR}" ]] ; then
+                mv -vi "${AUDIO_DIR}"/* "${DPX_DIR}" # move all files in the AUDIO directory to the DPX directory. -v=verbose, -i=interactive (prompts before overwriting)
+                rm -vri "${AUDIO_DIR}" # removes the AUDIO directory and any files left in it. -v=verbose, -r=recursive, -i=interactive (prompts before overwriting)
             fi
-            if [[ -d "${derivatives}" ]] ; then
-                mv -vi "${derivatives}"/* "${dpx}" # move all files in the derivatives directory to the DPX directory
-                rm -vri "${derivatives}" # removes the derivatives directory and any files left within it
-            printf "%s" "${color_off}"
+            if [[ -d "${DERIV_DIR}" ]] ; then
+                mv -vi "${DERIV_DIR}"/* "${DPX_DIR}" # move all files in the DERIVATIVES directory to the DPX directory
+                rm -vri "${DERIV_DIR}" # removes the DERIVATIVES directory and any files left within it
+            printf "%s" "${COLOR_OFF}"
             fi
         else
             echo
-            printf "%s%s is not a directory. Exiting" "${bired}" "${input}"
+            printf "%s%s is not a directory. Exiting" "${BIRED}" "${INPUT}"
             exit
         fi
         echo
-        if [[ -d "${md5}" ]] ; then
-            printf "Moving .md5 directory to %s%s%s\n" "${biyellow}" "${dpx}" "${color_off}"
+        if [[ -d "${MD5_DIR}" ]] ; then
+            printf "Moving .md5 directory to %s%s%s\n" "${BIYELLOW}" "${DPX_DIR}" "${COLOR_OFF}"
             echo
-            printf "%s" "${gray}"
-            rsync -avvPhi --stats "${md5}/${input##*/}"/*.md5 "${dpx}" # move .md5 directory to DPX directory to initiate DPX pickup. -a="archive," -vv=very verbose, -P=keep partially transferred files+show progress during transfer, -h=human-readable, -i=itemize changes
-            printf "%s" "${color_off}"
+            printf "%s" "${GRAY}"
+            rsync -avvPhi --stats "${MD5_DIR}/${INPUT##*/}"/*.md5 "${DPX_DIR}" # move .md5 directory to DPX directory to initiate DPX pickup. -a="archive," -vv=very verbose, -P=keep partially transferred files+show progress during transfer, -h=human-readable, -i=itemize changes
+            printf "%s" "${COLOR_OFF}"
             echo
-            printf "Done moving .md5 directory to %s%s%s.\nVFCU will begin picking up your files shortly." "${biyellow}" "${dpx}" "${color_off}"
+            printf "Done moving .md5 directory to %s%s%s.\nVFCU will begin picking up your files shortly." "${BIYELLOW}" "${DPX_DIR}" "${COLOR_OFF}"
             echo
-            printf "%sPlease make sure your templates have been set correctly!%s" "${bired}" "${color_off}"
+            printf "%sPlease make sure your templates have been set correctly!%s" "${BIRED}" "${COLOR_OFF}"
             echo
             cowsay "Tootles!"
         else
-            printf "%s%s does not exist. Exiting" "${bired}" "${md5}"
+            printf "%s%s does not exist. Exiting" "${BIRED}" "${MD5_DIR}"
             exit
         fi
         shift
@@ -91,5 +91,5 @@ _log -b
 restructureForVFCU "${@}"
 # log script ending
 _log -e
-printf "${biwhite}restructureForVFCU process complete.${color_off}\n"
+printf "${BIWHITE}restructureForVFCU process complete.${COLOR_OFF}\n"
 exit $?
diff --git a/verifySIP b/verifySIP
--- a/verifySIP
+++ b/verifySIP
@@ -3,15 +3,15 @@
 # verifySIP checks for key files in each SIP: the master file, the derivative file, and the MD5 file (if expected within that package)
 
 # load nmaahcmmfunctions into this script
-script_path=${0%/*}
-. "${script_path}/nmaahcmmfunctions"
-[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
+SCRIPT_PATH=${0%/*}
+. "${SCRIPT_PATH}/nmaahcmmfunctions"
+[[ -f "${SCRIPT_PATH}/nmaahcmmfunctions" ]] || { echo "Missing '${SCRIPT_PATH}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
 _setcolors # assigns colors using a function defined in nmaahcmmfunctions
 _initialize_make # safe script termination process defined in nmaahcmmfunctions
 
 ## USAGE
 
-usage(){
+_usage(){
     echo
     echo "$(basename "${0}")"
     echo
@@ -21,13 +21,13 @@ usage(){
     echo
     exit
 }
-[ "${#}" = 0 ] && usage # if the command is run with no arguments then usage is called
+[ "${#}" = 0 ] && _usage # if the command is run with no arguments then _usage is called
 # getopts loop
 OPTIND=1
 while getopts ":h" OPT; do
     case "${OPT}" in
-        h) usage ;;  # if the operator runs "[scriptname] -h" then the usage text above will display in the terminal
-        *) echo "Invalid option -${OPTARG}" ; usage ;; # if the operator tries to use an option other than the ones listed above, the usage text will display in the terminal
+        h) _usage ;;  # if the operator runs "[scriptname] -h" then the _usage text above will display in the terminal
+        *) echo "Invalid option -${OPTARG}" ; _usage ;; # if the operator tries to use an option other than the ones listed above, the _usage text will display in the terminal
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -51,7 +51,7 @@ _runtest(){
     RUN_ERR="${?}" # any stderr output by the xpath function
     if [[ "${RUN_ERR}" != 0 ]] ; then
         printf "${LABEL}" # the error message associated with each xpath query
-        printf "${bired}Error: Running: \"${*}\" gave an Error Code - ${RUN_ERR}${color_off}"
+        printf "${BIRED}Error: Running: \"${*}\" gave an Error Code - ${RUN_ERR}${COLOR_OFF}"
         echo "${XMLRESULT}"
     fi
     # if the xpath statement finds a file that the test is looking for (default test); || OR if the xpath statement does NOT find a file and the test is NOT looking for one (inverted test);
@@ -71,7 +71,7 @@ while [[ "${*}" != "" ]] ; do
     PACKAGE="${1}"
     shift
     if [[ -f "${PACKAGE}" ]] ; then
-        printf "${bired}The package you supplied is not a directory!${color_off}" 
+        printf "${BIRED}The package you supplied is not a directory!${COLOR_OFF}" 
     elif [[ -d "${PACKAGE}" ]] ; then
         MEDIAID=$(basename "${PACKAGE}")
         echo
@@ -88,7 +88,7 @@ while [[ "${*}" != "" ]] ; do
         if [[ -n "${XMLRESULT}" ]] ; then
             SIP="FILM_DPX"
             echo
-            printf "\n${biwhite}Checking for DPX package conformance...${color_off}\n"
+            printf "\n${BIWHITE}Checking for DPX package conformance...${COLOR_OFF}\n"
             # to be filled out with DPX package example
         fi
 
@@ -97,7 +97,7 @@ while [[ "${*}" != "" ]] ; do
         _runtest "Based on directory names, this SIP is digitized film in non-DPX format." xml sel -t -v "/tree/directory/directory[@name='MP4_2048x1152' or @name='ProRes_2048x1536']/@name" -n "${TEMPTREE}"
         if [[ -n "${XMLRESULT}" ]] ; then
             SIP="FILM_FILES"
-            printf "\n${biwhite}Checking for non-DPX film package conformance...${color_off}\n"
+            printf "\n${BIWHITE}Checking for non-DPX film package conformance...${COLOR_OFF}\n"
             _runtest -i "This package is missing a ProRes master file!" xml sel -t -v "/tree/directory/directory[@name='ProRes_2048x1536']/file[substring(@name,string-length(@name)-2)='mov']/@name" -n "${TEMPTREE}"
             _runtest -i "This package is missing an MP4 derivative file!" xml sel -t -v "/tree/directory/directory[@name='MP4_2048x1152']/file[substring(@name,string-length(@name)-2)='mp4']/@name" -n "${TEMPTREE}"
         fi
@@ -107,7 +107,7 @@ while [[ "${*}" != "" ]] ; do
         _runtest "Based on the presence of vrecord files, this SIP is digitized video." xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-13)='qctools.xml.gz' or substring(@name,string-length(@name)-19)='capture_options.log']/@name" -n "${TEMPTREE}"
         if [[ -n "${XMLRESULT}" ]] ; then
             SIP="VIDEO_VRECORD"
-            printf "\n${biwhite}Checking for digitized video package conformance...${color_off}\n"
+            printf "\n${BIWHITE}Checking for digitized video package conformance...${COLOR_OFF}\n"
             _runtest -i "This package is missing an MKV master file!" xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-2)='mkv']/@name" -n "${TEMPTREE}"
             _runtest -i "This package is missing an MP4 derivative file!" xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-2)='mp4']/@name" -n "${TEMPTREE}"
             _runtest -i "This package is missing a frameMD5 file!" xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-7)='framemd5']/@name" -n "${TEMPTREE}"
@@ -118,7 +118,7 @@ while [[ "${*}" != "" ]] ; do
         _runtest "Based on the presence of files with 'DV' in the filename, this SIP is transferred DV." xml sel -t -v "/tree/directory[@name='*DV*']/@name" -n "${TEMPTREE}"
         if [[ -n "${XMLRESULT}" ]] ; then
             SIP="VIDEO_DV"
-            printf "\b${biwhite}Checking for DV package conformance...${color_off}\n"
+            printf "\b${BIWHITE}Checking for DV package conformance...${COLOR_OFF}\n"
             _runtest -i "This package is missing an MOV master file!" xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-2)='mov']/@name" -n "${TEMPTREE}"
             _runtest -i "This package is missing an MP4 derivative file!" xml sel -t -v "/tree/directory/directory[@name='derivative']/file[substring(@name,string-length(@name)-2)='mp4']/@name" -n "${TEMPTREE}"
             _runtest -i "This package is missing an MD5 file!" xml sel -t -v "/tree/directory/file[substring(@name,string-length(@name)-2)='md5']/@name" -n "${TEMPTREE}"
@@ -138,4 +138,4 @@ done
 
 # log script ending
 _log -e
-printf "\n${biwhite}verifySIP process complete.${color_off}\n"
+printf "\n${BIWHITE}verifySIP process complete.${COLOR_OFF}\n"
