added EMPTY to .txt files

diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -13,16 +13,26 @@ color_off=$(tput sgr0)
 
 makedrivetree()
 {
-local drive ;
+local drive ; #set local variable $drive
+local folder=$HOME/Google_Drive/05_DriveContents/
   for drive ; do
+    	drive="${drive%/}" #strip trailing / if any
     if [ -d "$drive" ] ; then
-      output=$HOME/Google_Drive/05_DriveContents_TXT/${drive##*/}_contents_"$date".txt
-			if [ -d $output ] ; then
+      output=${drive##*/}_contents_"$date".txt
+      output="$folder/$output"
+			if [ -d $folder ] ; then
       	tree --filelimit 30 --si --du -U -Q -o "$output" "$drive"
-        printf "%sdone. moving to next drive.\n" "$biwhite" >&2
-				cp -va "$output" "$drive"
+        if grep "0 directories, 0 files" "$output" ; then
+          echo "$drive is empty" &&
+          outputE="$folder/${drive##*/}_contents_"$date"_EMPTY.txt" &&
+          mv -v "$output" "$outputE"
+          cp -v "$outputE" "$drive"
+        else
+          echo "$drive is not empty"
+          cp -va "$output" "$drive"
+        fi
 			else
-        printf "%sError $output does not exist\n" "$bired" >&2
+        printf "%sError $folder does not exist\n" "$bired" >&2
 				exit
       fi
     else
