Improve looping functionality in makeDer/makeH264
makeDer and makeH264 could see if a derivative is already made, but didn’t stop the script because of it (i.e., the interactive segments still happened). Scripts should immediately shift to next argument instead. This commit:
-Updates the scripts to skip the interactive process once existing derivatives are identified
-Updates script feedback to be more explicit about its progress (e.g., "moving to next file" previously appeared regardless of the actual number of arguments)
-Restructures the makeH264 script so that the script's actions are not contained within a function. (The function did not correctly loop over multiple arguments.) The makeH264 script may still be called from other scripts in the same folder, so removing the function did not change its portability.

diff --git a/makeH264 b/makeH264
--- a/makeH264
+++ b/makeH264
@@ -31,18 +31,18 @@ usage(){
 
 ### FUNCTIONS
 
-makeh264(){
-    #user_input="${*}" # i'm unclear what the purpose of this line is...so I commented it out
-    OPTIND=1 # command-line options to set mediaid and original variables
-    while getopts ":h" OPT ; do
-        case "${OPT}" in
-            h) _usage ;;
-            *) echo "bad option -${OPTARG}" ; _usage ;;
-            :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makeyoutube" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
-        esac
-    done
-    #shift $(( ${OPTIND} - 1 ))
-    shift "$((OPTIND-1))"
+#user_input="${*}" # i'm unclear what the purpose of this line is...so I commented it out
+OPTIND=1 # command-line options to set mediaid and original variables
+while getopts ":h" OPT ; do
+    case "${OPT}" in
+        h) _usage ;;
+        *) echo "bad option -${OPTARG}" ; _usage ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makeyoutube" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
+    esac
+done
+shift $(( ${OPTIND} - 1 ))
+
+while [ "${*}" != "" ] ; do
 
     input="${1}" #set $input as the first arugment sent to script
     if [[ -f "${input}" ]] ; then #if input is a file, set output_dir to input name with extension stripped plus relativepath
@@ -56,13 +56,13 @@ makeh264(){
     output="${output_dir}/${mediaid%.*}${suffix}.${extension}" #set $output
     if [ -s "${output}" ] ; then #check to see if $output exists
         printf "%sWARNING ${output} already exists, skipping transcode of %s.%s%s\n" "${bired}" "${input}" "${color_off}" "${biwhite}"
-        shift
-    fi
-    printf "%smediaid is: %s%s\n" "${color_off}" "${biwhite}" "${mediaid}"
-    printf "%sThe output directory is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir}"
-    printf "%soutput is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir/$mediaid%.*$suffix.$extension}"
+        printf "Moving to next file if present...\n${color_off}"
+    else
+        printf "%smediaid is: %s%s\n" "${color_off}" "${biwhite}" "${mediaid}"
+        printf "%sThe output directory is: %s%s\n" "${color_off}" "${biwhite}" "${output_dir}"
+        printf "%soutput is: %s%s\n" "${color_off}" "${biwhite}" "${output}"
 
-    echo
+        echo
 cat <<-EOF
     A CRF value needs specified.
     The range of the quantizer scale is 0-51: where 0 is lossless, 23 is default, and 51 is worst possible.
@@ -73,10 +73,10 @@ cat <<-EOF
     General usage is to choose the highest CRF value that still provides an acceptable quality.
     If the output looks good, then try a higher value and if it looks bad then choose a lower value.
 EOF
-    echo
-    printf "%sPlease enter a CRF value:%s\n" "${color_off}" "${biwhite}"
-    read -r crfvalue
-    echo
+        echo
+        printf "%sPlease enter a CRF value:%s\n" "${color_off}" "${biwhite}"
+        read -r crfvalue
+        echo
 cat <<-EOF
     A preset encoding speed needs specified.
     A preset is a collection of options that will provide a certain encoding speed to compression ratio.
@@ -87,36 +87,33 @@ cat <<-EOF
     The general guideline is to use the slowest preset that you have patience for.
     Current presets in descending order of speed are:
 EOF
-    printf "%sultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow\n" "${bired}"
-    #printf "%s" "${biwhite}"
-    echo
-    printf "%sPlease enter a preset speed:%s\n" "${color_off}" "${biwhite}"
-    read -r presetspeed
-    echo
+        printf "%sultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow\n" "${bired}"
+        #printf "%s" "${biwhite}"
+        echo
+        printf "%sPlease enter a preset speed:%s\n" "${color_off}" "${biwhite}"
+        read -r presetspeed
+        echo
 cat <<-EOF
     The maxrate speed is the max bitrate at which your video will be encoded. It is written in kbps.
     A good maxrate for Youtube type delivery is 8000.
 EOF
-    echo
-    printf "%sPlease enter a maxrate speed:%s\n" "${color_off}" "${biwhite}"
-    read -r maxrate
-    printf "\n%smaking .mp4 derivative of %s%s%s\n" "${color_off}" "${biwhite}" "${mediaid}" "${color_off}" #have script say what is about to do
-    mkdir -p "${output_dir}"
+        echo
+        printf "%sPlease enter a maxrate speed:%s\n" "${color_off}" "${biwhite}"
+        read -r maxrate
+        printf "\n%smaking .mp4 derivative of %s%s%s\n" "${color_off}" "${biwhite}" "${mediaid}" "${color_off}" #have script say what is about to do
+        mkdir -p "${output_dir}"
 
-    for file in "${@}" ; do
-        if [[ -f "${file}" ]]; then #run ffmpeg command on $input and set output to $output
+        if [[ -f "${input}" ]]; then #run ffmpeg command on $input and set output to $output
             # -vf scale=-2:1484
-            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${file}" -movflags faststart -c:v libx264 -vf "yadif,format=yuv420p" -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
-        elif [[ -d "${file}" ]]; then
-            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${file}"/*.mov -movflags faststart -pix_fmt yuv420p -c:v libx264 -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
+            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${input}" -movflags faststart -c:v libx264 -vf "yadif,format=yuv420p" -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
+        elif [[ -d "${input}" ]]; then
+            ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${input}"/*.mov -movflags faststart -pix_fmt yuv420p -c:v libx264 -crf "${crfvalue}" -preset "${presetspeed}" -maxrate "${maxrate}"k -bufsize 1835k -c:a aac -strict -2 -b:a 384k -f mp4 "${output}"
         fi
-        printf "\n%sdone. moving to next file.%s\n" "${biwhite}" "${color_off}"
-        shift
-    done
-}
+        printf "\nSuccess! Derivative ${biwhite}$(basename ${output})${color_off} created.\n\n"
+    fi
+    shift
+done
 
-#call the function(s)
-
-makeh264 "${@}"
+printf "${biwhite}makeH264 process complete.${color_off}\n"
 
 exit "$?"
