Change all tabs to 4 spaces; change 2-space “tabs” to 4 spaces; correct tabbing in nested functions
-Converted each tab character into 4 spaces.
-Converted tabs made with 2 spaces into 4-space tabs.
-Corrected some tabbing in if...then and for/while...done statements.

These changes were made to keep indentation identical in all text editors; text editors can usually handle all spaces or all tabs in a document, but not a combination of the two, and this may introduce bugs.

diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -15,30 +15,28 @@ makedrivetree()
 {
 local drive ; #set local variable $drive
 local folder=/Volumes/UtilitySAN/05_driveContents
-  for drive ; do
-    	drive="${drive%/}" #strip trailing / if any
+for drive ; do
+    drive="${drive%/}" #strip trailing / if any
     if [ -d "${drive}" ] ; then
-      output="${drive##*/}_contents_${date}.txt"
-      output="${folder}/${output}"
-			if [ -d "${folder}" ] ; then
-      	tree --filelimit 50 --si --du -U -Q -o "${output}" "${drive}"
-        if grep "0 directories, 0 files" "${output}" ; then
-          printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${biwhite}" "${drive}" "${color_off}" &&
-          outputE="${folder}/${drive##*/}_contents_${date}_EMPTY.txt" &&
-          mv -v "${output}" "${output}E"
-          printf "%sMoving %s to %s\n%s" "${biwhite}" "${outputE##*/}" "${drive}" "${color_off}"
-          cp -v "${outputE}" "${drive}"
-        else
-          printf "%s%s is not empty\n%s" "${biwhite}" "${drive}" "${color_off}"
-          cp -va "${output}" "${drive}"
-        fi
-			else
-        printf "%sError %s does not exist. Exiting.\n" "${bired}" "${folder}" >&2
-				exit
-      fi
+        output="${drive##*/}_contents_${date}.txt"
+        output="${folder}/${output}"
+            if [ -d "${folder}" ] ; then
+                tree --filelimit 50 --si --du -U -Q -o "${output}" "${drive}"
+                if grep "0 directories, 0 files" "${output}" ; then
+                    printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${biwhite}" "${drive}" "${color_off}" && outputE="${folder}/${drive##*/}_contents_${date}_EMPTY.txt" && mv -v "${output}" "${output}E"
+                    printf "%sMoving %s to %s\n%s" "${biwhite}" "${outputE##*/}" "${drive}" "${color_off}"
+                    cp -v "${outputE}" "${drive}"
+                else
+                    printf "%s%s is not empty\n%s" "${biwhite}" "${drive}" "${color_off}"
+                    cp -va "${output}" "${drive}"
+                fi
+            else
+                printf "%sError %s does not exist. Exiting.\n" "${bired}" "${folder}" >&2
+                exit
+            fi
     else
-      printf "%sError %s does not exist. Exiting.\n" "${bired}" "${drive}" >&2
-			exit
+        printf "%sError %s does not exist. Exiting.\n" "${bired}" "${drive}" >&2
+        exit
     fi
     
   done
