formatting fixes etc

diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -1,22 +1,41 @@
 #!/usr/bin/env bash
 
-DATE="$(date +%Y%m%d)"
+# a script to write the contents of a directory in tree form and save it to a .txt file
 
-while [ "${*}" != "" ] ; do
+### CONSTANTS
 
-	#set $DRIVE as the first arugment sent to script
-	DRIVE="${1}"
-	#set $OUTPUT
-	OUTPUT="/Users/medialab/Desktop/05_DriveContents_TXT/$(basename "${DRIVE}")_contents_"${DATE}".txt"
+date="$(date +%Y%m%d)"
 
-	tree -I "*.dpx" --si --du -U -o "${OUTPUT}" "${DRIVE}"
+### FUNCTIONS
 
-#	if ?=0; then
-		echo 'done. moving to next drive.'
-#		else
-#			echo 'error'
-#	fi
+makedrivetree ()
 
-	shift
+{
+	while [ "${*}" != "" ] ; do
 
-done
+		#set $DRIVE as the first arugment sent to script
+		drive="${1}"
+		#set $OUTPUT
+		output="/Users/medialab/Desktop/05_DriveContents_TXT/$(basename "${drive}")_contents_"${date}".txt"
+		#run tree
+		tree --filelimit 30 --si --du -U -Q -o "${output}" "${drive}"
+
+		#check $? for errors
+		if [ "$?" -eq "0" ] ; then
+			echo 'done. moving to next drive.'
+		else
+			echo 'error'
+		fi
+
+		shift
+
+	done
+}
+
+#call the function(s)
+
+makedrivetree "$@"
+
+echo 'makedrivetree exited with status' $?
+
+exit
diff --git a/moveDPX b/moveDPX
--- a/moveDPX
+++ b/moveDPX
@@ -9,19 +9,23 @@ while [ "${*}" != "" ] ; do
 	DPX_FOLDER="${INPUT}"
 	TARGET_FOLDER="/Users/medialab/Desktop/07_DPX_checksums"/$(basename "${DPX_FOLDER}")
 	mkdir -p "${TARGET_FOLDER}"
+
 	if [ ! -d "${TARGET_FOLDER}" ] ; then
-	echo -e "${BIWhite}"Creating "${TARGET_FOLDER}" "${Color_Off}"
-	echo
+		echo -e "${BIWhite}"Creating "${TARGET_FOLDER}" "${Color_Off}"
+		echo
 	fi
+
 	for file in "${DPX_FOLDER}"/*DPX*/* ; do
 		if [ -f "${TARGET_FOLDER}"/*.dpx ] ; then
 			echo -e "${BIWhite}"$(basename "$file") exists, verifying checksum"${Color_Off}"
 			rsync -aPhic "$file" "${TARGET_FOLDER}"
-		else rsync -aPhi "$file" "${TARGET_FOLDER}"
-		RSYNC_ERR_1="$?"
-		echo -e "rsync exited with "${RSYNC_ERR_1}""
+			RSYNC_ERR_1="$?"
+		else
+			rsync -aPhi "$file" "${TARGET_FOLDER}"
+			RSYNC_ERR_1="$?"
 		fi
-		echo -e "${BIWhite}"exit status is: "${RSYNC_ERR_1}""${Color_Off}"
+		echo -e "${BIWhite}"rsync exit status is: "${RSYNC_ERR_1}""${Color_Off}"
+
 		if [[ "${RSYNC_ERR_1}" == 0 ]]; then
 			#statements
 			echo -e "${BIWhite}"MOVED: $(basename "$file")
@@ -37,18 +41,20 @@ while [ "${*}" != "" ] ; do
 		if [ -f "${TARGET_FOLDER}"/*.md5 ] ; then
 			echo -e "${BIWhite}"$(basename "$md5") exists, verifying checksum"${Color_Off}"
 			rsync -aPhic "$md5" "${TARGET_FOLDER}"
-		else rsync -aPhi "$md5" "${TARGET_FOLDER}"
-		RSYNC_ERR_2="$?"
-		echo -e "rsync exited with "${RSYNC_ERR_2}""
+			RSYNC_ERR_2="$?"
+		else
+			rsync -aPhi "$md5" "${TARGET_FOLDER}"
+			RSYNC_ERR_2="$?"
 		fi
-		echo -e "${BIWhite}"exit status is: "${RSYNC_ERR_2}""${Color_Off}"
+			echo -e "${BIWhite}"rsync exit status is: "${RSYNC_ERR_2}""${Color_Off}"
+
 	 	if [[ "${RSYNC_ERR_2}" == 0 ]]; then
-	 			#statements
-				echo -e "${BIWhite}"MOVED: $(basename "$md5")
-				echo -e TO DIRECTORY: "${TARGET_FOLDER}""${Color_Off}"
-				echo
-			else
-				echo -e "${BIRed}"ERRORS"${Color_Off}"
+	 		#statements
+			echo -e "${BIWhite}"MOVED: $(basename "$md5")
+			echo -e TO DIRECTORY: "${TARGET_FOLDER}""${Color_Off}"
+			echo
+		else
+			echo -e "${BIRed}"ERRORS"${Color_Off}"
 		fi
 	done
 	echo -e "moving on"
