working

diff --git a/makedrivetree b/makedrivetree
--- a/makedrivetree
+++ b/makedrivetree
@@ -5,20 +5,42 @@
 ### CONSTANTS
 
 date="$(date +%Y%m%d)"
+biwhite='\e[1;97m'
+bired='\e[1;91m'
+color_off='\e[0m'
 
 ### FUNCTIONS
 
-makedrivetree ()
+makedrivetree()
+# {
+#	local drive ;
+#	if [ -d $drive ] ; then
+#		for drive ; do
+#			output=$HOME/Desktop/${drive##*/}_contents_${date}
+#			if tree --filelimit 30 --si --du -U -Q -o "${output}" "${drive}" ; then
+#					echo "done. moving to next drive" >&2
+#			else
+#					echo "error" >&2
+#			fi
+#	else
+#		echo -e $bired'Error' $drive 'does not exist.'$color_off
+#	fi
+#done
+# }
 
-{
+ {
 	while [ "${*}" != "" ] ; do
 
 		#set $DRIVE as the first arugment sent to script
 		drive="${1}"
 		#set $OUTPUT
-		output="/Users/medialab/Desktop/05_DriveContents_TXT/$(basename "${drive}")_contents_"${date}".txt"
+		output="$HOME/Desktop/05_DriveContents_TXT/$(basename "${drive}")_contents_"${date}".txt"
 		#run tree
-		tree --filelimit 30 --si --du -U -Q -o "${output}" "${drive}"
+		if [ -d $drive ] ; then
+			tree --filelimit 30 --si --du -U -Q -o "${output}" "${drive}"
+		else
+			echo -e $bired'Error' $drive 'does not exist.'$color_off
+		fi
 
 		#check $? for errors
 		if [ "$?" -eq "0" ] ; then
