clean up selection of profile

diff --git a/mkvnote b/mkvnote
--- a/mkvnote
+++ b/mkvnote
@@ -141,11 +141,37 @@ EOF
 exit
 }
 
+# Variable initialization for selected profile and tag set.
+SELECTED_PROFILE=""
+SELECTED_TAG_SET=()
+
+# command-line options to set media id and original variables
+OPTIND=1
+while getopts ":hp:" opt ; do
+    case "${opt}" in
+        p) SELECTED_PROFILE="${OPTARG}" ;;
+        h) _usage ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _usage ; exit 1 ;;
+        *) echo "bad option -${OPTARG}" ; _usage ; exit 1 ;;
+    esac
+done
+shift "$((OPTIND-1))"
+
 # Checks if the script was run without any arguments.
 # If no arguments are provided, the _usage function is called to display usage information and the script exits.
 
 if [[ "${#}" -eq 0 ]]; then
     _usage
+fi
+
+# Parsing command line options to set the profile and corresponding tag set.
+if [[ "${SELECTED_PROFILE}" == "jpc" ]] ; then
+    SELECTED_TAG_SET=("${MKV_TAG_SET_JPC[@]}")
+elif [[ "${SELECTED_PROFILE}" == "nmaahc" ]] ; then
+    SELECTED_TAG_SET=("${MKV_TAG_SET_NMAAHC[@]}")
+else
+    unset SELECTED_PROFILE # clear the invalid profiles since it's not one of the ones listed in the if/elif conditions above
+    echo -e "${BOLD}${ERROR}\nNote: Invalid profile or no profile specified with -p. You will be prompted to select a profile.${RESET}"
 fi
 
 # Function _maketemp creates a temporary file and checks for success.
@@ -159,56 +185,42 @@ _maketemp(){
     fi
 }
 
-selected_profile=""
-selected_tag_set=""
-
-# Parse command line options
-while [[ $# -gt 0 ]]; do
-    case "$1" in
-        -p|--profile)
-            case "$2" in
-                jpc)
-                    selected_tag_set=("${MKV_TAG_SET_JPC[@]}")
-                    selected_profile="jpc"
-                    ;;
-                nmaahc)
-                    selected_tag_set=("${MKV_TAG_SET_NMAAHC[@]}")
-                    selected_profile="nmaahc"
-                    ;;
-                *)
-                    echo -e "\033[1;31m\nYou must specify a profile using -p or --profile followed by 'jpc' or 'nmaahc'.\n\033[0m"
-                    echo -e "\nHere are the profiles and their respective tags:\n"
-                    echo -e "\"jpc\" profile tags:"
-                    for TAG in "${MKV_TAG_SET_JPC[@]}" ; do
-                        echo -e "\t- $TAG"
-                    done
-                    echo -e "\n\"nmaahc\" profile tags:"
-                    for TAG in "${MKV_TAG_SET_NMAAHC[@]}" ; do
-                        echo -e "\t- $TAG"
-                    done
-                    exit 1
-                    ;;
-            esac
-            shift 2
-            ;;
-        *)
-            break
-            ;;
-    esac
-done
-
-if [ -z "$selected_profile" ]; then
-    echo -e "\033[1;31m\nYou must specify a profile using -p or --profile followed by 'jpc' or 'nmaahc'.\n\033[0m"
-    echo -e "Here are the profiles and their respective tags:\n"
-    echo -e "\"jpc\" profile tags:"
-    for TAG in "${MKV_TAG_SET_JPC[@]}" ; do
-        echo -e "\t- $TAG"
+# Display available tag options and prompt for selection if no profile was selected
+if [ -z "${SELECTED_PROFILE}" ]; then
+    echo -e "${GB}\nAvailable tag profiles and their respective tags:${RESET}"
+    echo -e "${BOLD}\n1) JPC profile tags:${RESET}"
+    for TAG in "${MKV_TAG_SET_JPC[@]}"; do
+        echo -e "    - $TAG"
     done
-    echo -e "\n\"nmaahc\" profile tags:"
-    for TAG in "${MKV_TAG_SET_NMAAHC[@]}" ; do
-        echo -e "\t- $TAG"
+    echo -e "${BOLD}\n2) NMAAHC profile tags:${RESET}"
+    for TAG in "${MKV_TAG_SET_NMAAHC[@]}"; do
+        echo -e "    - $TAG"
     done
-    exit 1
+
+    while true; do
+        echo -e "${GB}${BOLD}\nYou must select a tag profile."
+        echo -e "Press 1 for JPC, 2 for NMAAHC, or 0 to exit.\n"
+        read -p "Enter your choice: " choice
+        case "$choice" in
+            1)
+                SELECTED_TAG_SET=("${MKV_TAG_SET_JPC[@]}")
+                SELECTED_PROFILE="jpc"
+                break # Exit the loop after selection
+                ;;
+            2)
+                SELECTED_TAG_SET=("${MKV_TAG_SET_NMAAHC[@]}")
+                SELECTED_PROFILE="nmaahc"
+                break # Exit the loop after selection
+                ;;
+            0)
+                echo -e "${ERROR}\nExiting...${RESET}"
+                exit 0
+                ;;
+            *)
+                echo "Invalid choice. Please try again."
+                ;;
+        esac
+    done
 fi
 
 MKV_FILE="${1}"
