new script

diff --git a/moveDPX b/moveDPX
--- a/moveDPX
+++ b/moveDPX
@@ -9,30 +9,47 @@ while [ "${*}" != "" ] ; do
 	DPX_FOLDER="${INPUT}"
 	TARGET_FOLDER="/Users/medialab/Desktop/07_DPX_checksums"/$(basename "${DPX_FOLDER}")
 	mkdir -p "${TARGET_FOLDER}"
+	echo -e "${BIWhite}"Creating "${TARGET_FOLDER}" "${Color_Off}"
 	echo
 	for file in "${DPX_FOLDER}"/*DPX*/* ; do
 		if [ -f "${TARGET_FOLDER}"/*.dpx ] ; then
-			echo -e "${BIWhite}"$(basename "$file") exists, verifying checksum
+			echo -e "${BIWhite}"$(basename "$file") exists, verifying checksum"${Color_Off}"
 			rsync -aPhic "$file" "${TARGET_FOLDER}"
 		else rsync -aPhi "$file" "${TARGET_FOLDER}"
-		echo -e MOVED: $(basename "$file")
-		echo -e TO DIRECTORY: "${TARGET_FOLDER}" "${Color_Off}"
+		RSYNC_ERR_1="$?"
+		fi
+		echo -e "${BIWhite}"exit status is: "${RSYNC_ERR_1}""${Color_Off}"
+		if [[ "${RSYNC_ERR_1}" == 0 ]]; then
+			#statements
+			echo -e "${BIWhite}"MOVED: $(basename "$file")
+		  echo -e TO DIRECTORY: "${TARGET_FOLDER}""${Color_Off}"
+		  echo
+	 	else
+			echo -e "${BIRed}"ERRORS"${Color_Off}"
 		fi
 		break 1
 	done
+
 	for md5 in "${DPX_FOLDER}"/*.md5 ; do
 		if [ -f "${TARGET_FOLDER}"/*.md5 ] ; then
-			echo -e "${BIWhite}" $(basename "$md5") exists, verifying checksum
+			echo -e "${BIWhite}"$(basename "$md5") exists, verifying checksum"${Color_Off}"
 			rsync -aPhic "$md5" "${TARGET_FOLDER}"
-		else
-			rsync -aPhi "$md5" "${TARGET_FOLDER}"
-		echo -e MOVED: $(basename "$md5")
-		echo -e TO DIRECTORY: "${TARGET_FOLDER}" "${Color_Off}"
+		else rsync -aPhi "$md5" "${TARGET_FOLDER}"
+		RSYNC_ERR_2="$?"
+		fi
+		echo -e "${BIWhite}"exit status is: "${RSYNC_ERR_2}""${Color_Off}"
+	 	if [[ "${RSYNC_ERR_2}" == 0 ]]; then
+	 			#statements
+				echo -e "${BIWhite}"MOVED: $(basename "$md5")
+				echo -e TO DIRECTORY: "${TARGET_FOLDER}""${Color_Off}"
+				echo
+			else
+				echo -e "${BIRed}"ERRORS"${Color_Off}"
 		fi
 	done
 	shift
 done
-
+echo
 echo -e "${BIWhite}"changed permissions on the following files in directory $(basename "${CHMOD_FOLDER}") to 777:
 CHMOD_FOLDER="/Users/medialab/Desktop/07_DPX_checksums"
 chmod -vR 777 "${CHMOD_FOLDER}"
