Create _log function and call it for start/end
A log of the start and end time of each function being run will be kept in "~/Desktop/logs/nmaahcmm.log."

diff --git a/nmaahcmmfunctions b/nmaahcmmfunctions
--- a/nmaahcmmfunctions
+++ b/nmaahcmmfunctions
@@ -125,3 +125,28 @@ function _check_deliverdir(){
         printf "${bired}" "The delivery directory, ${DELIVERDIR}, does not exist. Can not deliver the OUTPUT of $(basename "${0}")." "${color_off}"
     fi
 }
+
+function _log(){
+    LOGDIR="~/Desktop/logs"
+    if [[ ! -d "${LOGDIR}" ]] ; then
+        mkdir "${LOGDIR}"
+        if [[ "${?}" -ne 0 ]] ; then
+            echo "${0}: Can't create log directory at ${LOGDIR}, exiting..."
+            exit 1
+        fi
+    fi
+    LOGNAME="nmaahcmm.log"
+    OPTIND=1
+    while getopts ":beacw" OPT; do
+        case "${OPT}" in
+            b) STATUS="start" ;;              # script is beginning
+            e) STATUS="end"   ;;              # script is ending
+            a) STATUS="abort" ;;              # script is aborted
+            c) STATUS="comment" ;;            # comment about what script is doing
+            w) STATUS="warning" ;;            # warning information
+        esac
+    done
+    shift $(( ${OPTIND} - 1 ))
+    NOTE="${1}"
+    echo "$(date +%FT%T), $(basename "${0}"), ${STATUS}, ${OP}, ${MEDIAID}, ${NOTE}" >> "${LOGDIR}/${LOGNAME}"
+}
