add _maketemp function
Called in verifySIP.

diff --git a/nmaahcmmfunctions b/nmaahcmmfunctions
--- a/nmaahcmmfunctions
+++ b/nmaahcmmfunctions
@@ -150,3 +150,12 @@ function _log(){
     NOTE="${1}"
     echo "$(date +%FT%T), $(basename "${0}"), ${STATUS}, ${OP}, ${MEDIAID}, ${NOTE}" >> "${LOGDIR}/${LOGNAME}"
 }
+
+function _maketemp(){
+    mktemp -q "/tmp/$(basename "${0}").XXXXXX"
+    if [ "${?}" -ne 0 ]; then
+        echo "${0}: Can't create temp file, exiting..."
+        _writeerrorlog "_maketemp" "was unable to create the temp file, so the script had to exit."
+        exit 1
+    fi
+}
